<a href="https://colab.research.google.com/github/First-555/BSC_DPDM2025/blob/main/Midterm_663020586_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# ข้อ1

In [1]:
import pandas as pd

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [3]:
import os
os.chdir('/content/drive/MyDrive/BSC_2025/Mid')
!pwd # เช็ค path ที่กำลังทำงานอยู่

/content/drive/MyDrive/BSC_2025/Mid

In [4]:
Dailyrain = pd.read_csv('/content/drive/MyDrive/BSC_2025/Mid/Daily rain - (Statistics 2012-2024)/hii_daily_rain.csv')
Dailyrain.head()

,station_code,measure_datetime,data,station_name,latitude,longitude,quality_flag,basin,sub_basin,tambon,amphoe,province,data_type
0,ABRT,2012-01-01 07:00:00+07,0.0,วัดเวฬุวัน,16.054785,103.66429,U,ชี,ลำน้ำชีส่วนที่ 4/2,เหนือเมือง,เมืองร้อยเอ็ด,ร้อยเอ็ด,rainfall_daily
1,ABRT,2012-01-03 07:00:00+07,0.0,วัดเวฬุวัน,16.054785,103.66429,U,ชี,ลำน้ำชีส่วนที่ 4/2,เหนือเมือง,เมืองร้อยเอ็ด,ร้อยเอ็ด,rainfall_daily
2,ABRT,2012-01-06 07:00:00+07,0.0,วัดเวฬุวัน,16.054785,103.66429,U,ชี,ลำน้ำชีส่วนที่ 4/2,เหนือเมือง,เมืองร้อยเอ็ด,ร้อยเอ็ด,rainfall_daily
3,ABRT,2012-01-07 07:00:00+07,0.0,วัดเวฬุวัน,16.054785,103.66429,U,ชี,ลำน้ำชีส่วนที่ 4/2,เหนือเมือง,เมืองร้อยเอ็ด,ร้อยเอ็ด,rainfall_daily
4,ABRT,2012-01-08 07:00:00+07,0.0,วัดเวฬุวัน,16.054785,103.66429,U,ชี,ลำน้ำชีส่วนที่ 4/2,เหนือเมือง,เมืองร้อยเอ็ด,ร้อยเอ็ด,rainfall_daily

In [9]:
print(f"จำนวนแถวทั้งหมดของ Dailyrain: {Dailyrain.shape[0]}")

จำนวนแถวทั้งหมดของ Dailyrain: 3768463

รายละเอียดคอลัมน์ในชุดข้อมูล

station_code: รหัสประจำสถานีตรวจวัด (เช่น ABRT) ใช้เป็นตัวระบุอ้างอิงของสถานีนั้น ๆ

measure_datetime: วันและเวลาที่ทำการตรวจวัดข้อมูล ในที่นี้คือรูปแบบ ปี-เดือน-วัน ตามด้วยเวลา (ส่วนใหญ่เป็น 07:00:00+07 ซึ่งเป็นเวลามาตรฐานในการสรุปยอดน้ำฝนรายวันของไทย)

data: ค่าปริมาณน้ำฝนที่วัดได้ หน่วยโดยทั่วไปจะเป็น มิลลิเมตร (mm)

station_name: ชื่อของสถานีตรวจวัด (เช่น วัดเวฬุวัน)

latitude / longitude: ค่าพิกัดทางภูมิศาสตร์ (ละติจูดและลองจิจูด) เพื่อบอกตำแหน่งที่ตั้งของสถานีบนแผนที่

quality_flag: เครื่องหมายระบุคุณภาพของข้อมูล (เช่น 'U' อาจหมายถึง Unverified หรือข้อมูลที่ยังไม่ได้ผ่านการตรวจสอบยืนยันความถูกต้องอย่างเป็นทางการ)

basin: ชื่อลุ่มน้ำหลัก (เช่น ลุ่มน้ำชี)

sub_basin: ชื่อลุ่มน้ำย่อย (เช่น ลำน้ำชีส่วนที่ 4/2)

tambon: ชื่อตำบลที่สถานีตั้งอยู่ (เช่น เหนือเมือง)

amphoe: ชื่ออำเภอที่สถานีตั้งอยู่ (เช่น เมืองร้อยเอ็ด)

province: ชื่อจังหวัดที่สถานีตั้งอยู่ (เช่น ร้อยเอ็ด)

data_type: ประเภทของข้อมูล ในที่นี้คือ rainfall_daily หรือข้อมูลน้ำฝนรายวัน

In [5]:
input = pd.read_csv('/content/drive/MyDrive/BSC_2025/Mid/Input - (Operation Daily rain from API_ 2025)/Stations in the model_HII.csv')
input.head()

   Node        Lat        Long
0  ACRU  15.788054  104.642235
1  BBHN   9.536913   98.579490
2  BBUA  17.372976  103.984436
3  BCNG  17.386840  103.290870
4  BDAR  14.587073  102.495190

In [8]:
unique_station_codes = filtered_Dailyrain['station_code'].unique()
display(unique_station_codes)
print(f"มี station_code ทั้งหมด {len(unique_station_codes)} รายการ")

array(['ACRU', 'BBHN', 'BBUA', 'BCNG', 'BDAR', 'BDCP', 'BDGN', 'BDLH',
       'BDMG', 'BGRT', 'BHMN', 'BHRA', 'BHUN', 'BJIG', 'BKDN', 'BKHL',
       'BKHN', 'BKK001', 'BKK008', 'BKK009', 'BKK015', 'BKK017', 'BKK018',
       'BKK019', 'BKUG', 'BKWN', 'BLAT', 'BLKO', 'BLUG', 'BMDG', 'BMNK',
       'BNAN', 'BNGR', 'BNHG', 'BNHI', 'BNHO', 'BNKN', 'BNKP', 'BNLG',
       'BNMK', 'BNPI', 'BNPU', 'BNTK', 'BOKA', 'BPIA', 'BPK004', 'BPLA',
       'BPPS', 'BPTG', 'BRKM', 'BSBA', 'BSDE', 'BSKJ', 'BSMP', 'BSPN',
       'BSUM', 'BTHO', 'BWKG', 'BYNU', 'CATK', 'CBUR', 'CCSS', 'CEHM',
       'CGDO', 'CGKM', 'CGMN', 'CGSN', 'CHHA', 'CHI005', 'CHI010',
       'CHI011', 'CHI012', 'CHI013', 'CHM001', 'CHM002', 'CHM003',
       'CHM004', 'CHN004', 'CHNA', 'CHPA', 'CHR003', 'CHR004', 'CHR005',
       'CHUN', 'CLPK', 'CMSG', 'CPKC', 'CPY003', 'CPY004', 'CPY009',
       'CPY010', 'CPY012', 'CPY013', 'CPY015', 'CPY017', 'CSMO', 'CTKN',
       'DCCT', 'DGSL', 'DITO', 'DIV001', 'DIV002', 'DIV003', 'DIV004',
       'DIV005', 'DKLG', 'DKTI', 'DMKH', 'DNCM', 'DSKT', 'DTAN', 'HCTT',
       'HKTG', 'HNKA', 'HNRE', 'HSYO', 'HTTM', 'HUYG', 'HYOD', 'HYRT',
       'JBLG', 'KABG', 'KAHN', 'KAKG', 'KANG', 'KAOP', 'KGKG', 'KGLN',
       'KHHM', 'KHPB', 'KKHA', 'KKPA', 'KKTO', 'KKWF', 'KMSI', 'KNYM',
       'KOKN', 'KOLO', 'KON002', 'KON004', 'KON005', 'KOSB', 'KOSK',
       'KOSR', 'KPEM', 'KRKM', 'KRN002', 'KSOD', 'KSPS', 'KTKB', 'KTLE',
       'KWSI', 'LBI002', 'LEEE', 'LK13', 'LMPN', 'LMSK', 'LNRG', 'LPLE',
       'MCHI', 'MCRM', 'MDTG', 'MECN', 'MEPK', 'MEWG', 'MKTR', 'MMMO',
       'MMNY', 'MNRM', 'MRMT', 'MUN011', 'MUN014', 'NAKU', 'NAMN',
       'NAN001', 'NAN006', 'NAN010', 'NAN011', 'NAN012', 'NAN013',
       'NAN014', 'NANI', 'NAPJ', 'NAPK', 'NASW', 'NBON', 'NEAK', 'NGBA',
       'NGCG', 'NGCH', 'NGNG', 'NGPI', 'NKMT', 'NKNN', 'NKO001', 'NKO002',
       'NKOK', 'NKSG', 'NKTI', 'NKYG', 'NMKH', 'NMKI', 'NMPR', 'NMPT',
       'NNKO', 'NNPT', 'NOKK', 'NPCT', 'NPI001', 'NPI002', 'NPNK', 'NPSD',
       'NSRS', 'NTAN', 'NTNG', 'NTST', 'NYK000', 'PAI002', 'PAII',
       'PAS001', 'PAS002', 'PAS008', 'PASG', 'PDAM', 'PGKH', 'PHON',
       'PHPS', 'PICI', 'PIN003', 'PIN004', 'PIN005', 'PIN006', 'PLTL',
       'PMPN', 'PONG', 'PPAN', 'PPCT', 'PPRM', 'PPTC', 'PRC002', 'PRC003',
       'PRGB', 'PRN001', 'PSLI', 'PSLT', 'PTLE', 'PTWY', 'PYMR', 'PYO001',
       'RAJ002', 'RAY001', 'RBPI', 'RGKG', 'RIKK', 'RNG001', 'RNGH',
       'SAY001', 'SAY002', 'SBT1', 'SENM', 'SGKW', 'SISU', 'SITP',
       'SKE001', 'SKE002', 'SKE003', 'SKG002', 'SKG005', 'SKG007', 'SKKG',
       'SKM004', 'SKM005', 'SLA002', 'SLBC', 'SMSU', 'SNGT', 'SNKO',
       'SOKL', 'SPPT', 'SPWA', 'SRKT', 'SSRG', 'STH004', 'STH005',
       'STH011', 'STH014', 'STH016', 'STH017', 'STH018', 'STH022',
       'STH025', 'STH029', 'STH030', 'STU001', 'STWN', 'SVI001', 'SVI002',
       'SWAR', 'SWH1', 'SWKL', 'SWNG', 'SYTL', 'TAPE', 'TEPT', 'TETN',
       'TGLG', 'TGSK', 'THA001', 'THA003', 'THA006', 'THA010', 'THA011',
       'THCG', 'THNG', 'THNM', 'THTN', 'TKFA', 'TKNT', 'TKRA', 'TLAN',
       'TLPC', 'TMLI', 'TNG001', 'TNG002', 'TOGO', 'TON001', 'TON006',
       'TPI001', 'TPI002', 'TPI004', 'TPI005', 'TPI007', 'TPPN', 'TPTN',
       'TPUR', 'TRD001', 'TRD002', 'TRON', 'TSLM', 'TSUD', 'TTKO', 'TTLG',
       'TTWY', 'TUKW', 'VLGE01', 'VLGE03', 'VLGE07', 'VLGE14', 'VLGE27',
       'VLGE29', 'VLGE31', 'VLGE32', 'VLGE33', 'VLGE41', 'VLGE42',
       'WAN001', 'WAN002', 'WAN005', 'WBYN', 'WCBR', 'WCHN', 'WCTK',
       'WEI071', 'WGCI', 'WGKN', 'WGNA', 'WGTG', 'WNKH', 'WNMI', 'WPAP',
       'WRRS', 'WSPN', 'WTBT', 'WTCH', 'WTLG', 'WTSG', 'WWST', 'YCUM',
       'YGHM', 'YOM001', 'YOM003', 'YOM008', 'YOM009', 'YOM010', 'YOM012'],
      dtype=object)

มี station_code ทั้งหมด 385 รายการ

Node: รหัสสถานี (เหมือนกับ station_code ในภาพที่แล้ว)

Lat (Latitude): ค่าพิกัดละติจูด

Long (Longitude): ค่าพิกัดลองจิจูด

In [15]:
output = pd.read_csv('/content/drive/MyDrive/BSC_2025/Mid/Output - (Clean monthly rain - 2025)/Y_monthly_rain_HII_operation.csv')
output.head()

   Node   rain  month  year
0  ACRU   83.0      7  2025
1  ACRU  164.8      8  2025
2  ACRU  248.6      9  2025
3  ACRU   48.4     10  2025
4  ACRU   52.2     11  2025

Node: รหัสสถานี เพื่อใช้เชื่อมโยงกับพิกัดในตาราง input

rain: ปริมาณน้ำฝนรวม (Total Rainfall) ของเดือนนั้น ๆ

month: ลำดับของเดือน (เช่น 7 คือเดือนกรกฎาคม, 8 คือเดือนสิงหาคม)

year: ปี ค.ศ. (ในภาพคือปี 2025)

# ข้อ2

In [6]:
filtered_Dailyrain = Dailyrain[Dailyrain['station_code'].isin(input['Node'])]
print(filtered_Dailyrain.head())

     station_code        measure_datetime  data station_name   latitude  \
3488         ACRU  2012-01-01 07:00:00+07   0.0     ทต.ไก่คำ  15.788054
3489         ACRU  2012-01-06 07:00:00+07   0.0     ทต.ไก่คำ  15.788054
3490         ACRU  2012-01-07 07:00:00+07   0.0     ทต.ไก่คำ  15.788054
3491         ACRU  2012-01-08 07:00:00+07   0.0     ทต.ไก่คำ  15.788054
3492         ACRU  2012-01-09 07:00:00+07   0.0     ทต.ไก่คำ  15.788054

       longitude quality_flag basin sub_basin tambon           amphoe  \
3488  104.642235            U   มูล    ลำเซบก  ไก่คำ  เมืองอำนาจเจริญ
3489  104.642235            U   มูล    ลำเซบก  ไก่คำ  เมืองอำนาจเจริญ
3490  104.642235            U   มูล    ลำเซบก  ไก่คำ  เมืองอำนาจเจริญ
3491  104.642235            U   มูล    ลำเซบก  ไก่คำ  เมืองอำนาจเจริญ
3492  104.642235            U   มูล    ลำเซบก  ไก่คำ  เมืองอำนาจเจริญ

        province       data_type
3488  อำนาจเจริญ  rainfall_daily
3489  อำนาจเจริญ  rainfall_daily
3490  อำนาจเจริญ  rainfall_daily
3491  อำนาจเจริญ  rainfall_daily
3492  อำนาจเจริญ  rainfall_daily

In [7]:
display(filtered_Dailyrain.head())
print(f"จำนวนแถวทั้งหมด: {filtered_Dailyrain.shape[0]}")

,station_code,measure_datetime,data,station_name,latitude,longitude,quality_flag,basin,sub_basin,tambon,amphoe,province,data_type
3488,ACRU,2012-01-01 07:00:00+07,0.0,ทต.ไก่คำ,15.788054,104.642235,U,มูล,ลำเซบก,ไก่คำ,เมืองอำนาจเจริญ,อำนาจเจริญ,rainfall_daily
3489,ACRU,2012-01-06 07:00:00+07,0.0,ทต.ไก่คำ,15.788054,104.642235,U,มูล,ลำเซบก,ไก่คำ,เมืองอำนาจเจริญ,อำนาจเจริญ,rainfall_daily
3490,ACRU,2012-01-07 07:00:00+07,0.0,ทต.ไก่คำ,15.788054,104.642235,U,มูล,ลำเซบก,ไก่คำ,เมืองอำนาจเจริญ,อำนาจเจริญ,rainfall_daily
3491,ACRU,2012-01-08 07:00:00+07,0.0,ทต.ไก่คำ,15.788054,104.642235,U,มูล,ลำเซบก,ไก่คำ,เมืองอำนาจเจริญ,อำนาจเจริญ,rainfall_daily
3492,ACRU,2012-01-09 07:00:00+07,0.0,ทต.ไก่คำ,15.788054,104.642235,U,มูล,ลำเซบก,ไก่คำ,เมืองอำนาจเจริญ,อำนาจเจริญ,rainfall_daily

จำนวนแถวทั้งหมด: 1662282

In [10]:
print(f"จำนวนสถานีก่อนกรอง: {Dailyrain.shape[0]}")
print(f"จำนวนสถานีหลังกรอง: {filtered_Dailyrain.shape[0]}")

จำนวนสถานีก่อนกรอง: 3768463
จำนวนสถานีหลังกรอง: 1662282

# ข้อ3

In [27]:
# ตรวจสอบและแปลงคอลัมน์ 'measure_datetime' ให้เป็น datetime object หากยังไม่ได้แปลง
if not pd.api.types.is_datetime64_any_dtype(filtered_Dailyrain['measure_datetime']):
    filtered_Dailyrain['measure_datetime'] = pd.to_datetime(filtered_Dailyrain['measure_datetime'])

# Group by station and find missing dates
missing_records_summary = {}

for station_code, group in filtered_Dailyrain.groupby('station_code'):
    # Get the min and max date for the current station
    min_date = group['measure_datetime'].min()
    max_date = group['measure_datetime'].max()

    # Create a complete date range for this station (inclusive of min_date and max_date)
    full_date_range = pd.date_range(start=min_date.normalize(), end=max_date.normalize(), freq='D')
    total_expected_days = len(full_date_range)

    # Get the unique dates present in the data for this station
    present_dates = group['measure_datetime'].dt.normalize().unique()

    # Find the missing dates
    missing_dates = full_date_range[~full_date_range.isin(present_dates)]
    missing_count = len(missing_dates)

    if missing_count > 0:
        missing_proportion = (missing_count / total_expected_days) * 100
        missing_records_summary[station_code] = {
            'count': missing_count,
            'proportion': f"{missing_proportion:.2f}%",
            'example_missing_dates': missing_dates.tolist()[:5] # Show up to 5 example missing dates
        }

if missing_records_summary:
    print("สรุปข้อมูล Record ที่หายไปของแต่ละสถานี:")
    # Sort by the number of missing records for better readability
    sorted_summary = sorted(missing_records_summary.items(), key=lambda item: item[1]['count'], reverse=True)
    for station, summary in sorted_summary:
        print(f"- สถานี {station}: ข้อมูลหายไป {summary['count']} วัน ({summary['proportion']})")
        if summary['example_missing_dates']:
            print(f"  ตัวอย่างวันที่หายไป: {', '.join([d.strftime('%Y-%m-%d') for d in summary['example_missing_dates']])}")
else:
    print("ไม่พบข้อมูล Record ที่หายไปในสถานีใดๆ")

สรุปข้อมูล Record ที่หายไปของแต่ละสถานี:
- สถานี BPLA: ข้อมูลหายไป 962 วัน (20.39%)
  ตัวอย่างวันที่หายไป: 2012-01-02, 2012-01-04, 2012-01-05, 2012-08-15, 2012-08-16
- สถานี BHMN: ข้อมูลหายไป 822 วัน (17.43%)
  ตัวอย่างวันที่หายไป: 2012-01-02, 2012-03-21, 2012-03-22, 2012-03-23, 2012-03-24
- สถานี KHHM: ข้อมูลหายไป 798 วัน (16.96%)
  ตัวอย่างวันที่หายไป: 2012-01-14, 2012-01-16, 2012-01-17, 2012-01-18, 2012-01-20
- สถานี BKHN: ข้อมูลหายไป 779 วัน (16.60%)
  ตัวอย่างวันที่หายไป: 2012-03-13, 2012-03-14, 2012-03-15, 2012-03-16, 2012-03-17
- สถานี STH005: ข้อมูลหายไป 777 วัน (17.61%)
  ตัวอย่างวันที่หายไป: 2014-05-28, 2014-08-17, 2014-08-31, 2015-04-04, 2015-04-27
- สถานี CHI011: ข้อมูลหายไป 763 วัน (16.26%)
  ตัวอย่างวันที่หายไป: 2012-12-01, 2012-12-02, 2012-12-03, 2012-12-04, 2012-12-05
- สถานี KHPB: ข้อมูลหายไป 759 วัน (16.09%)
  ตัวอย่างวันที่หายไป: 2012-01-02, 2012-01-04, 2012-01-05, 2012-07-06, 2012-07-07
- สถานี BKWN: ข้อมูลหายไป 739 วัน (15.67%)
  ตัวอย่างวันที่หายไป: 2012-01-02, 2012-01-04, 2012-01-05, 2012-06-02, 2012-06-03
- สถานี NKO001: ข้อมูลหายไป 729 วัน (16.03%)
  ตัวอย่างวันที่หายไป: 2012-06-22, 2012-06-23, 2012-06-24, 2012-06-25, 2012-06-26
- สถานี PAS002: ข้อมูลหายไป 716 วัน (15.78%)
  ตัวอย่างวันที่หายไป: 2014-09-25, 2014-09-26, 2014-09-27, 2014-09-28, 2014-09-29
- สถานี SAY002: ข้อมูลหายไป 715 วัน (15.72%)
  ตัวอย่างวันที่หายไป: 2012-06-22, 2012-06-23, 2012-06-24, 2012-06-25, 2012-06-26
- สถานี KOKN: ข้อมูลหายไป 711 วัน (15.07%)
  ตัวอย่างวันที่หายไป: 2012-01-02, 2012-01-04, 2012-01-05, 2014-03-30, 2014-04-25
- สถานี TKRA: ข้อมูลหายไป 708 วัน (15.01%)
  ตัวอย่างวันที่หายไป: 2012-01-02, 2012-01-04, 2012-01-05, 2013-09-12, 2013-09-13
- สถานี BNMK: ข้อมูลหายไป 683 วัน (15.16%)
  ตัวอย่างวันที่หายไป: 2012-08-01, 2012-08-02, 2012-08-03, 2012-08-04, 2012-08-05
- สถานี WTLG: ข้อมูลหายไป 676 วัน (14.33%)
  ตัวอย่างวันที่หายไป: 2012-01-02, 2012-01-03, 2012-01-04, 2012-01-05, 2012-05-13
- สถานี NKOK: ข้อมูลหายไป 668 วัน (14.16%)
  ตัวอย่างวันที่หายไป: 2012-01-02, 2012-01-09, 2012-01-10, 2012-01-11, 2012-01-12
- สถานี STH029: ข้อมูลหายไป 660 วัน (14.96%)
  ตัวอย่างวันที่หายไป: 2013-06-08, 2013-06-09, 2013-06-10, 2013-06-11, 2013-06-12
- สถานี BPPS: ข้อมูลหายไป 638 วัน (13.53%)
  ตัวอย่างวันที่หายไป: 2012-01-02, 2012-01-03, 2012-01-04, 2012-01-05, 2012-11-30
- สถานี VLGE07: ข้อมูลหายไป 622 วัน (13.19%)
  ตัวอย่างวันที่หายไป: 2012-03-01, 2012-03-02, 2012-03-03, 2012-03-04, 2012-03-05
- สถานี STH017: ข้อมูลหายไป 620 วัน (14.05%)
  ตัวอย่างวันที่หายไป: 2012-12-17, 2012-12-18, 2012-12-19, 2012-12-20, 2012-12-21
- สถานี KKHA: ข้อมูลหายไป 610 วัน (12.93%)
  ตัวอย่างวันที่หายไป: 2012-01-02, 2012-01-04, 2012-01-05, 2012-08-21, 2012-08-22
- สถานี NKYG: ข้อมูลหายไป 607 วัน (12.87%)
  ตัวอย่างวันที่หายไป: 2012-01-04, 2012-01-05, 2012-03-27, 2012-08-02, 2012-08-31
- สถานี SGKW: ข้อมูลหายไป 603 วัน (12.78%)
  ตัวอย่างวันที่หายไป: 2012-01-02, 2012-01-04, 2012-01-05, 2012-11-30, 2014-04-26
- สถานี THNM: ข้อมูลหายไป 603 วัน (12.78%)
  ตัวอย่างวันที่หายไป: 2012-01-02, 2012-07-27, 2012-07-28, 2012-07-29, 2012-07-30
- สถานี TPTN: ข้อมูลหายไป 598 วัน (12.68%)
  ตัวอย่างวันที่หายไป: 2012-01-02, 2012-01-04, 2012-01-05, 2013-12-16, 2013-12-17
- สถานี TTWY: ข้อมูลหายไป 597 วัน (12.66%)
  ตัวอย่างวันที่หายไป: 2012-01-02, 2012-01-04, 2012-01-05, 2014-03-16, 2014-04-13
- สถานี BNHI: ข้อมูลหายไป 596 วัน (12.64%)
  ตัวอย่างวันที่หายไป: 2012-01-02, 2012-01-04, 2013-01-29, 2013-01-30, 2013-01-31
- สถานี DITO: ข้อมูลหายไป 583 วัน (12.36%)
  ตัวอย่างวันที่หายไป: 2012-01-02, 2012-01-04, 2012-01-05, 2012-09-12, 2012-09-13
- สถานี BNTK: ข้อมูลหายไป 579 วัน (12.27%)
  ตัวอย่างวันที่หายไป: 2012-01-02, 2012-01-04, 2012-01-05, 2012-11-30, 2014-04-27
- สถานี SKKG: ข้อมูลหายไป 555 วัน (11.77%)
  ตัวอย่างวันที่หายไป: 2012-01-02, 2012-01-04, 2012-01-05, 2012-06-15, 2012-06-16
- สถานี NKSG: ข้อมูลหายไป 554 วัน (11.74%)
  ตัวอย่างวันที่หายไป: 2012-01-02, 2012-01-04, 2012-01-05, 2012-03-27, 2012-07-08
- สถานี MEWG: ข้อมูลหายไป 544 วัน (11.53%)
  ตัวอย่างวันที่หายไป: 2012-01-02, 2012-03-27, 2012-04-08, 2012-04-09, 2012-04-10
- สถานี KAOP: ข้อมูลหายไป 542 วัน (11.49%)
  ตัวอย่างวันที่หายไป: 2012-01-02, 2012-11-30, 2013-10-30, 2014-03-30, 2014-04-27
- สถานี BNPI: ข้อมูลหายไป 534 วัน (11.93%)
  ตัวอย่างวันที่หายไป: 2012-11-30, 2013-11-01, 2013-11-02, 2013-11-03, 2013-11-04
- สถานี STWN: ข้อมูลหายไป 533 วัน (11.30%)
  ตัวอย่างวันที่หายไป: 2012-01-02, 2012-01-04, 2012-01-05, 2012-06-19, 2012-06-20
- สถานี STH014: ข้อมูลหายไป 528 วัน (11.96%)
  ตัวอย่างวันที่หายไป: 2014-06-10, 2015-04-04, 2015-04-27, 2016-05-10, 2016-06-04
- สถานี NAPK: ข้อมูลหายไป 527 วัน (11.17%)
  ตัวอย่างวันที่หายไป: 2012-01-02, 2012-01-04, 2012-01-05, 2012-03-27, 2012-04-28
- สถานี DKLG: ข้อมูลหายไป 508 วัน (10.77%)
  ตัวอย่างวันที่หายไป: 2012-01-02, 2012-01-04, 2012-01-05, 2012-03-25, 2012-03-26
- สถานี MRMT: ข้อมูลหายไป 504 วัน (10.68%)
  ตัวอย่างวันที่หายไป: 2012-01-02, 2012-01-04, 2012-01-05, 2012-03-27, 2014-04-27
- สถานี MDTG: ข้อมูลหายไป 503 วัน (10.73%)
  ตัวอย่างวันที่หายไป: 2012-03-12, 2012-03-13, 2012-03-14, 2012-03-15, 2012-03-16
- สถานี KKTO: ข้อมูลหายไป 501 วัน (10.62%)
  ตัวอย่างวันที่หายไป: 2012-01-02, 2012-01-04, 2012-01-05, 2012-07-08, 2012-07-09
- สถานี LNRG: ข้อมูลหายไป 498 วัน (10.56%)
  ตัวอย่างวันที่หายไป: 2012-01-02, 2012-01-03, 2012-01-04, 2012-01-05, 2012-03-27
- สถานี TTLG: ข้อมูลหายไป 498 วัน (10.56%)
  ตัวอย่างวันที่หายไป: 2012-01-02, 2012-01-04, 2012-01-05, 2013-12-30, 2013-12-31
- สถานี BYNU: ข้อมูลหายไป 496 วัน (10.52%)
  ตัวอย่างวันที่หายไป: 2012-11-30, 2013-11-04, 2013-11-05, 2013-11-06, 2013-11-07
- สถานี CHR003: ข้อมูลหายไป 496 วัน (11.53%)
  ตัวอย่างวันที่หายไป: 2014-04-06, 2015-07-06, 2015-07-07, 2015-07-08, 2015-07-09
- สถานี WNKH: ข้อมูลหายไป 489 วัน (10.37%)
  ตัวอย่างวันที่หายไป: 2012-12-15, 2012-12-16, 2012-12-17, 2012-12-18, 2012-12-19
- สถานี YOM009: ข้อมูลหายไป 488 วัน (10.35%)
  ตัวอย่างวันที่หายไป: 2013-07-29, 2013-07-30, 2013-07-31, 2013-08-01, 2013-08-02
- สถานี KTKB: ข้อมูลหายไป 486 วัน (10.31%)
  ตัวอย่างวันที่หายไป: 2012-01-04, 2012-01-08, 2012-01-11, 2012-01-12, 2012-01-13
- สถานี SNGT: ข้อมูลหายไป 479 วัน (10.15%)
  ตัวอย่างวันที่หายไป: 2012-01-02, 2012-01-04, 2012-07-11, 2012-07-12, 2012-07-13
- สถานี VLGE27: ข้อมูลหายไป 479 วัน (11.37%)
  ตัวอย่างวันที่หายไป: 2013-05-19, 2014-03-16, 2014-04-13, 2015-02-25, 2015-02-26
- สถานี NPI001: ข้อมูลหายไป 473 วัน (10.07%)
  ตัวอย่างวันที่หายไป: 2012-03-27, 2013-09-10, 2013-09-11, 2013-09-12, 2013-09-13
- สถานี STH018: ข้อมูลหายไป 472 วัน (10.71%)
  ตัวอย่างวันที่หายไป: 2014-06-08, 2014-08-27, 2015-04-04, 2015-04-27, 2015-09-01
- สถานี BNHG: ข้อมูลหายไป 470 วัน (9.96%)
  ตัวอย่างวันที่หายไป: 2012-01-02, 2012-01-04, 2012-01-05, 2012-06-26, 2012-06-27
- สถานี WRRS: ข้อมูลหายไป 470 วัน (9.97%)
  ตัวอย่างวันที่หายไป: 2012-01-04, 2012-01-05, 2012-01-07, 2012-01-08, 2012-03-29
- สถานี CPY017: ข้อมูลหายไป 469 วัน (10.30%)
  ตัวอย่างวันที่หายไป: 2012-06-12, 2012-06-13, 2012-06-14, 2012-06-15, 2012-06-16
- สถานี TUKW: ข้อมูลหายไป 463 วัน (9.82%)
  ตัวอย่างวันที่หายไป: 2012-01-04, 2012-01-08, 2012-01-09, 2012-01-10, 2012-01-11
- สถานี CHI005: ข้อมูลหายไป 459 วัน (9.73%)
  ตัวอย่างวันที่หายไป: 2012-04-12, 2012-04-13, 2012-04-17, 2012-04-18, 2012-04-19
- สถานี CGMN: ข้อมูลหายไป 456 วัน (10.08%)
  ตัวอย่างวันที่หายไป: 2012-09-28, 2012-09-29, 2012-09-30, 2012-10-01, 2012-10-02
- สถานี DIV001: ข้อมูลหายไป 453 วัน (11.09%)
  ตัวอย่างวันที่หายไป: 2013-09-29, 2013-09-30, 2013-10-01, 2013-10-02, 2013-10-03
- สถานี BKK008: ข้อมูลหายไป 449 วัน (9.86%)
  ตัวอย่างวันที่หายไป: 2012-06-14, 2012-06-15, 2012-06-16, 2012-06-17, 2012-06-18
- สถานี SRKT: ข้อมูลหายไป 448 วัน (9.50%)
  ตัวอย่างวันที่หายไป: 2012-01-02, 2012-01-04, 2012-01-05, 2012-09-19, 2012-09-20
- สถานี CHUN: ข้อมูลหายไป 447 วัน (9.48%)
  ตัวอย่างวันที่หายไป: 2012-01-02, 2012-01-04, 2012-01-05, 2012-08-26, 2012-08-27
- สถานี PRN001: ข้อมูลหายไป 447 วัน (10.35%)
  ตัวอย่างวันที่หายไป: 2014-05-20, 2014-05-21, 2014-05-22, 2014-05-23, 2014-05-24
- สถานี TRON: ข้อมูลหายไป 444 วัน (9.62%)
  ตัวอย่างวันที่หายไป: 2012-04-17, 2012-04-18, 2012-04-19, 2012-04-20, 2012-04-21
- สถานี TPI002: ข้อมูลหายไป 437 วัน (9.31%)
  ตัวอย่างวันที่หายไป: 2014-04-13, 2014-08-21, 2014-08-22, 2014-08-23, 2014-08-24
- สถานี PIN004: ข้อมูลหายไป 429 วัน (9.11%)
  ตัวอย่างวันที่หายไป: 2012-11-10, 2012-11-11, 2012-11-12, 2012-11-13, 2012-11-14
- สถานี WCTK: ข้อมูลหายไป 426 วัน (9.05%)
  ตัวอย่างวันที่หายไป: 2012-01-02, 2012-01-04, 2014-03-16, 2014-04-01, 2014-04-13
- สถานี PASG: ข้อมูลหายไป 419 วัน (8.88%)
  ตัวอย่างวันที่หายไป: 2012-01-02, 2012-01-03, 2012-01-04, 2012-01-05, 2012-11-30
- สถานี KMSI: ข้อมูลหายไป 416 วัน (8.82%)
  ตัวอย่างวันที่หายไป: 2012-01-02, 2012-01-04, 2012-01-05, 2013-04-26, 2013-04-27
- สถานี NTNG: ข้อมูลหายไป 414 วัน (9.11%)
  ตัวอย่างวันที่หายไป: 2012-07-03, 2012-07-04, 2012-07-05, 2012-07-06, 2012-07-08
- สถานี SBT1: ข้อมูลหายไป 412 วัน (8.73%)
  ตัวอย่างวันที่หายไป: 2012-01-02, 2012-01-04, 2012-01-05, 2012-11-30, 2014-04-26
- สถานี DGSL: ข้อมูลหายไป 411 วัน (8.71%)
  ตัวอย่างวันที่หายไป: 2012-01-02, 2012-01-04, 2012-01-05, 2012-11-07, 2012-11-08
- สถานี STU001: ข้อมูลหายไป 410 วัน (9.02%)
  ตัวอย่างวันที่หายไป: 2012-06-22, 2012-06-23, 2012-06-24, 2012-06-25, 2012-06-26
- สถานี BKHL: ข้อมูลหายไป 407 วัน (8.63%)
  ตัวอย่างวันที่หายไป: 2012-01-02, 2012-01-04, 2012-01-05, 2014-04-27, 2014-12-25
- สถานี CPY012: ข้อมูลหายไป 405 วัน (8.91%)
  ตัวอย่างวันที่หายไป: 2013-07-31, 2013-08-01, 2013-08-02, 2013-08-03, 2013-08-04
- สถานี THA006: ข้อมูลหายไป 405 วัน (8.89%)
  ตัวอย่างวันที่หายไป: 2012-06-14, 2012-06-15, 2012-06-16, 2012-06-17, 2012-06-18
- สถานี SSRG: ข้อมูลหายไป 398 วัน (8.44%)
  ตัวอย่างวันที่หายไป: 2012-09-29, 2012-09-30, 2012-10-01, 2012-10-02, 2012-10-03
- สถานี WAN002: ข้อมูลหายไป 397 วัน (8.46%)
  ตัวอย่างวันที่หายไป: 2012-03-24, 2012-03-25, 2014-03-16, 2014-04-01, 2014-04-13
- สถานี THA003: ข้อมูลหายไป 392 วัน (8.61%)
  ตัวอย่างวันที่หายไป: 2012-06-13, 2012-06-14, 2012-06-15, 2012-06-16, 2012-06-17
- สถานี KNYM: ข้อมูลหายไป 390 วัน (8.27%)
  ตัวอย่างวันที่หายไป: 2012-01-04, 2012-01-05, 2012-04-16, 2012-04-17, 2012-04-18
- สถานี JBLG: ข้อมูลหายไป 389 วัน (8.25%)
  ตัวอย่างวันที่หายไป: 2012-01-02, 2012-01-04, 2012-01-05, 2012-10-13, 2012-10-14
- สถานี HCTT: ข้อมูลหายไป 388 วัน (8.23%)
  ตัวอย่างวันที่หายไป: 2012-01-02, 2012-01-03, 2012-01-04, 2012-01-05, 2012-11-30
- สถานี HYRT: ข้อมูลหายไป 388 วัน (8.23%)
  ตัวอย่างวันที่หายไป: 2012-01-02, 2012-01-04, 2012-01-05, 2012-07-06, 2012-07-07
- สถานี STH011: ข้อมูลหายไป 388 วัน (8.79%)
  ตัวอย่างวันที่หายไป: 2015-04-04, 2015-04-27, 2015-06-30, 2016-02-29, 2016-05-10
- สถานี STH022: ข้อมูลหายไป 388 วัน (8.79%)
  ตัวอย่างวันที่หายไป: 2013-10-18, 2013-10-19, 2013-10-20, 2013-10-21, 2013-10-22
- สถานี TNG002: ข้อมูลหายไป 387 วัน (8.51%)
  ตัวอย่างวันที่หายไป: 2012-06-22, 2012-06-23, 2012-06-24, 2012-06-25, 2012-06-26
- สถานี KGKG: ข้อมูลหายไป 386 วัน (8.48%)
  ตัวอย่างวันที่หายไป: 2012-06-26, 2012-06-27, 2012-06-28, 2012-06-29, 2012-06-30
- สถานี NASW: ข้อมูลหายไป 386 วัน (8.18%)
  ตัวอย่างวันที่หายไป: 2012-01-02, 2012-01-04, 2012-01-05, 2012-02-26, 2012-02-27
- สถานี BLAT: ข้อมูลหายไป 385 วัน (8.16%)
  ตัวอย่างวันที่หายไป: 2012-01-02, 2012-01-04, 2012-01-05, 2014-04-27, 2014-12-25
- สถานี KANG: ข้อมูลหายไป 384 วัน (8.32%)
  ตัวอย่างวันที่หายไป: 2012-04-26, 2012-04-27, 2012-04-28, 2012-04-29, 2012-04-30
- สถานี HNKA: ข้อมูลหายไป 382 วัน (8.10%)
  ตัวอย่างวันที่หายไป: 2012-01-02, 2012-01-04, 2012-03-28, 2012-03-29, 2012-03-30
- สถานี KON002: ข้อมูลหายไป 381 วัน (8.37%)
  ตัวอย่างวันที่หายไป: 2012-06-16, 2012-06-17, 2012-06-18, 2012-06-19, 2012-06-20
- สถานี KON005: ข้อมูลหายไป 380 วัน (8.35%)
  ตัวอย่างวันที่หายไป: 2012-06-16, 2012-06-17, 2012-06-18, 2012-06-19, 2012-06-20
- สถานี YCUM: ข้อมูลหายไป 380 วัน (8.06%)
  ตัวอย่างวันที่หายไป: 2012-01-02, 2012-01-04, 2012-01-05, 2013-08-06, 2013-08-07
- สถานี THCG: ข้อมูลหายไป 379 วัน (8.03%)
  ตัวอย่างวันที่หายไป: 2012-01-02, 2012-01-04, 2012-01-05, 2014-04-13, 2014-04-26
- สถานี BLKO: ข้อมูลหายไป 369 วัน (7.87%)
  ตัวอย่างวันที่หายไป: 2013-06-05, 2013-06-07, 2013-06-08, 2013-06-09, 2013-06-10
- สถานี KOSR: ข้อมูลหายไป 369 วัน (7.82%)
  ตัวอย่างวันที่หายไป: 2012-01-02, 2012-01-04, 2012-01-05, 2014-03-30, 2014-04-27
- สถานี RBPI: ข้อมูลหายไป 369 วัน (7.82%)
  ตัวอย่างวันที่หายไป: 2012-01-02, 2012-01-04, 2012-01-05, 2012-03-27, 2012-11-30
- สถานี TSUD: ข้อมูลหายไป 367 วัน (7.79%)
  ตัวอย่างวันที่หายไป: 2014-03-16, 2014-04-13, 2014-04-27, 2014-07-15, 2014-07-16
- สถานี BPTG: ข้อมูลหายไป 366 วัน (7.76%)
  ตัวอย่างวันที่หายไป: 2012-01-02, 2012-01-04, 2012-01-05, 2012-11-30, 2013-08-06
- สถานี MECN: ข้อมูลหายไป 366 วัน (7.93%)
  ตัวอย่างวันที่หายไป: 2012-05-12, 2012-05-13, 2012-05-14, 2012-05-15, 2012-05-16
- สถานี BPIA: ข้อมูลหายไป 364 วัน (7.72%)
  ตัวอย่างวันที่หายไป: 2012-01-02, 2012-01-04, 2012-01-05, 2012-11-30, 2014-02-06
- สถานี CHI010: ข้อมูลหายไป 364 วัน (7.72%)
  ตัวอย่างวันที่หายไป: 2013-05-23, 2013-05-24, 2013-05-25, 2013-05-26, 2013-05-27
- สถานี BHRA: ข้อมูลหายไป 363 วัน (7.70%)
  ตัวอย่างวันที่หายไป: 2012-01-02, 2012-01-03, 2012-01-04, 2012-01-05, 2014-04-27
- สถานี TEPT: ข้อมูลหายไป 362 วัน (7.67%)
  ตัวอย่างวันที่หายไป: 2012-01-02, 2012-01-03, 2012-01-04, 2012-01-05, 2012-01-22
- สถานี TPPN: ข้อมูลหายไป 361 วัน (7.65%)
  ตัวอย่างวันที่หายไป: 2012-01-02, 2012-01-04, 2012-01-05, 2012-10-29, 2012-10-30
- สถานี CEHM: ข้อมูลหายไป 360 วัน (7.63%)
  ตัวอย่างวันที่หายไป: 2012-01-02, 2012-01-03, 2012-01-04, 2012-01-05, 2012-11-30
- สถานี BNAN: ข้อมูลหายไป 357 วัน (7.86%)
  ตัวอย่างวันที่หายไป: 2012-07-03, 2012-07-04, 2012-07-07, 2012-07-09, 2012-07-11
- สถานี TPUR: ข้อมูลหายไป 355 วัน (7.53%)
  ตัวอย่างวันที่หายไป: 2012-01-02, 2012-01-03, 2012-01-04, 2012-01-05, 2012-07-03
- สถานี DMKH: ข้อมูลหายไป 353 วัน (7.48%)
  ตัวอย่างวันที่หายไป: 2012-01-02, 2012-11-30, 2014-04-06, 2014-04-14, 2014-04-27
- สถานี SAY001: ข้อมูลหายไป 352 วัน (7.74%)
  ตัวอย่างวันที่หายไป: 2012-06-22, 2012-06-23, 2012-06-24, 2012-06-25, 2012-06-26
- สถานี STH004: ข้อมูลหายไป 352 วัน (7.98%)
  ตัวอย่างวันที่หายไป: 2015-04-04, 2015-04-27, 2016-05-10, 2016-06-04, 2016-06-17
- สถานี PONG: ข้อมูลหายไป 350 วัน (7.44%)
  ตัวอย่างวันที่หายไป: 2012-01-14, 2012-01-16, 2012-01-17, 2012-01-18, 2012-01-20
- สถานี STH030: ข้อมูลหายไป 345 วัน (7.82%)
  ตัวอย่างวันที่หายไป: 2014-04-13, 2015-04-04, 2015-04-27, 2015-07-22, 2015-09-01
- สถานี NSRS: ข้อมูลหายไป 344 วัน (7.29%)
  ตัวอย่างวันที่หายไป: 2012-01-02, 2012-01-03, 2012-01-04, 2012-01-05, 2012-03-27
- สถานี CPY009: ข้อมูลหายไป 343 วัน (7.55%)
  ตัวอย่างวันที่หายไป: 2012-08-31, 2012-09-01, 2012-09-02, 2012-09-03, 2012-09-04
- สถานี BDAR: ข้อมูลหายไป 341 วัน (7.23%)
  ตัวอย่างวันที่หายไป: 2012-01-02, 2012-01-04, 2012-01-05, 2012-10-31, 2013-06-05
- สถานี THTN: ข้อมูลหายไป 341 วัน (7.23%)
  ตัวอย่างวันที่หายไป: 2012-01-02, 2012-01-04, 2012-01-05, 2012-10-30, 2012-10-31
- สถานี BKUG: ข้อมูลหายไป 340 วัน (7.21%)
  ตัวอย่างวันที่หายไป: 2012-01-02, 2012-01-03, 2012-01-04, 2012-01-05, 2014-04-27
- สถานี BSDE: ข้อมูลหายไป 340 วัน (7.21%)
  ตัวอย่างวันที่หายไป: 2012-01-02, 2012-11-30, 2014-04-27, 2016-05-11, 2016-09-08
- สถานี NMKH: ข้อมูลหายไป 339 วัน (7.24%)
  ตัวอย่างวันที่หายไป: 2012-11-30, 2013-05-25, 2013-05-26, 2013-05-27, 2013-05-28
- สถานี BSUM: ข้อมูลหายไป 336 วัน (7.12%)
  ตัวอย่างวันที่หายไป: 2012-01-02, 2012-07-04, 2012-07-05, 2012-07-06, 2012-07-07
- สถานี TPI005: ข้อมูลหายไป 336 วัน (7.16%)
  ตัวอย่างวันที่หายไป: 2014-04-13, 2016-05-10, 2016-07-01, 2016-07-02, 2016-07-26
- สถานี LBI002: ข้อมูลหายไป 335 วัน (7.37%)
  ตัวอย่างวันที่หายไป: 2012-06-16, 2012-06-17, 2012-06-18, 2012-06-19, 2012-06-20
- สถานี CTKN: ข้อมูลหายไป 333 วัน (7.06%)
  ตัวอย่างวันที่หายไป: 2012-01-02, 2012-01-04, 2012-01-05, 2012-11-30, 2014-04-06
- สถานี HYOD: ข้อมูลหายไป 333 วัน (7.06%)
  ตัวอย่างวันที่หายไป: 2012-01-02, 2012-01-04, 2012-01-05, 2012-11-30, 2014-03-30
- สถานี TNG001: ข้อมูลหายไป 333 วัน (7.32%)
  ตัวอย่างวันที่หายไป: 2012-06-20, 2012-06-21, 2012-06-22, 2012-06-23, 2012-06-24
- สถานี TKNT: ข้อมูลหายไป 332 วัน (7.06%)
  ตัวอย่างวันที่หายไป: 2012-05-22, 2012-05-23, 2012-05-24, 2012-05-25, 2012-05-26
- สถานี PIN003: ข้อมูลหายไป 329 วัน (6.98%)
  ตัวอย่างวันที่หายไป: 2015-04-04, 2015-04-27, 2015-05-27, 2016-05-11, 2016-05-12
- สถานี CHM001: ข้อมูลหายไป 328 วัน (7.21%)
  ตัวอย่างวันที่หายไป: 2012-06-22, 2012-06-23, 2012-06-24, 2012-06-25, 2012-06-26
- สถานี CMSG: ข้อมูลหายไป 328 วัน (7.25%)
  ตัวอย่างวันที่หายไป: 2012-11-30, 2014-04-06, 2014-04-27, 2014-07-16, 2014-07-17
- สถานี BBHN: ข้อมูลหายไป 324 วัน (6.87%)
  ตัวอย่างวันที่หายไป: 2012-01-02, 2012-01-04, 2012-01-05, 2012-10-31, 2014-04-02
- สถานี CPKC: ข้อมูลหายไป 322 วัน (6.83%)
  ตัวอย่างวันที่หายไป: 2012-01-02, 2012-01-03, 2012-01-04, 2012-01-05, 2012-11-30
- สถานี MCRM: ข้อมูลหายไป 322 วัน (6.83%)
  ตัวอย่างวันที่หายไป: 2012-01-02, 2012-01-04, 2012-01-05, 2012-03-27, 2012-06-20
- สถานี PRC002: ข้อมูลหายไป 322 วัน (7.10%)
  ตัวอย่างวันที่หายไป: 2012-07-03, 2012-07-04, 2012-07-05, 2012-07-06, 2012-07-07
- สถานี SKG002: ข้อมูลหายไป 322 วัน (7.07%)
  ตัวอย่างวันที่หายไป: 2012-06-14, 2012-06-15, 2012-06-16, 2012-06-17, 2012-06-18
- สถานี CGKM: ข้อมูลหายไป 318 วัน (6.74%)
  ตัวอย่างวันที่หายไป: 2012-01-02, 2012-11-30, 2014-04-27, 2015-04-22, 2015-09-15
- สถานี HKTG: ข้อมูลหายไป 318 วัน (6.74%)
  ตัวอย่างวันที่หายไป: 2012-01-02, 2012-01-04, 2012-01-05, 2012-11-30, 2014-03-30
- สถานี PIN006: ข้อมูลหายไป 318 วัน (7.76%)
  ตัวอย่างวันที่หายไป: 2013-09-13, 2013-09-14, 2013-09-15, 2013-09-16, 2013-09-17
- สถานี BSPN: ข้อมูลหายไป 317 วัน (6.76%)
  ตัวอย่างวันที่หายไป: 2012-11-30, 2014-04-27, 2016-05-11, 2017-02-04, 2017-04-08
- สถานี KWSI: ข้อมูลหายไป 315 วัน (6.68%)
  ตัวอย่างวันที่หายไป: 2012-01-02, 2012-01-04, 2012-01-05, 2012-03-27, 2014-04-26
- สถานี CHR005: ข้อมูลหายไป 311 วัน (7.23%)
  ตัวอย่างวันที่หายไป: 2014-01-31, 2014-02-01, 2014-02-02, 2014-02-03, 2014-02-04
- สถานี YOM001: ข้อมูลหายไป 310 วัน (6.58%)
  ตัวอย่างวันที่หายไป: 2013-04-01, 2013-04-02, 2013-04-03, 2013-04-04, 2013-04-05
- สถานี CGSN: ข้อมูลหายไป 309 วัน (6.80%)
  ตัวอย่างวันที่หายไป: 2012-07-03, 2012-07-04, 2012-07-05, 2012-07-06, 2012-07-07
- สถานี NAKU: ข้อมูลหายไป 307 วัน (6.51%)
  ตัวอย่างวันที่หายไป: 2012-01-02, 2012-01-04, 2012-01-05, 2012-03-27, 2012-05-15
- สถานี PAS008: ข้อมูลหายไป 307 วัน (6.73%)
  ตัวอย่างวันที่หายไป: 2015-03-21, 2015-03-22, 2015-03-23, 2015-03-24, 2015-03-25
- สถานี TPI001: ข้อมูลหายไป 306 วัน (6.52%)
  ตัวอย่างวันที่หายไป: 2013-02-14, 2013-02-15, 2013-02-16, 2013-02-17, 2013-02-18
- สถานี WSPN: ข้อมูลหายไป 304 วัน (6.45%)
  ตัวอย่างวันที่หายไป: 2012-01-03, 2012-01-04, 2012-07-03, 2012-07-04, 2012-07-05
- สถานี BSKJ: ข้อมูลหายไป 302 วัน (6.75%)
  ตัวอย่างวันที่หายไป: 2012-11-30, 2014-04-27, 2016-05-11, 2016-09-08, 2016-09-09
- สถานี YGHM: ข้อมูลหายไป 302 วัน (6.40%)
  ตัวอย่างวันที่หายไป: 2012-01-02, 2012-01-05, 2013-03-31, 2013-04-01, 2013-04-02
- สถานี SENM: ข้อมูลหายไป 300 วัน (6.36%)
  ตัวอย่างวันที่หายไป: 2012-01-02, 2012-01-05, 2012-11-30, 2013-05-20, 2013-05-21
- สถานี PAS001: ข้อมูลหายไป 298 วัน (6.57%)
  ตัวอย่างวันที่หายไป: 2013-11-03, 2013-11-04, 2013-11-05, 2013-11-06, 2013-11-07
- สถานี SISU: ข้อมูลหายไป 295 วัน (6.25%)
  ตัวอย่างวันที่หายไป: 2012-01-02, 2012-11-30, 2014-04-27, 2015-04-04, 2016-05-11
- สถานี BKK019: ข้อมูลหายไป 294 วัน (6.81%)
  ตัวอย่างวันที่หายไป: 2014-12-25, 2016-01-30, 2016-01-31, 2016-02-01, 2016-02-02
- สถานี SITP: ข้อมูลหายไป 293 วัน (6.21%)
  ตัวอย่างวันที่หายไป: 2012-01-02, 2012-01-04, 2012-01-05, 2012-11-30, 2014-04-27
- สถานี NAN013: ข้อมูลหายไป 292 วัน (6.79%)
  ตัวอย่างวันที่หายไป: 2016-05-11, 2016-06-17, 2016-06-29, 2016-07-01, 2016-07-02
- สถานี BKK001: ข้อมูลหายไป 291 วัน (6.50%)
  ตัวอย่างวันที่หายไป: 2012-06-16, 2012-06-17, 2012-06-18, 2012-06-19, 2012-06-20
- สถานี LK13: ข้อมูลหายไป 291 วัน (6.17%)
  ตัวอย่างวันที่หายไป: 2012-01-02, 2012-01-04, 2012-01-05, 2012-03-27, 2013-02-16
- สถานี BMNK: ข้อมูลหายไป 290 วัน (6.15%)
  ตัวอย่างวันที่หายไป: 2012-01-02, 2012-01-03, 2012-01-04, 2012-01-05, 2012-01-08
- สถานี CLPK: ข้อมูลหายไป 290 วัน (6.15%)

# ข้อ4

In [42]:
print("สถานีที่มีข้อมูลหายไปมากกว่าหรือเท่ากับ 20%:")
found_stations = False
for station, summary in sorted_summary:
    # Convert proportion string to float for comparison
    proportion_float = float(summary['proportion'].replace('%', ''))
    if proportion_float >= 20.00:
        print(f"- สถานี {station}: ข้อมูลหายไป {summary['proportion']}")
        if summary['example_missing_dates']:
            print(f"  ตัวอย่างวันที่หายไป: {', '.join([d.strftime('%Y-%m-%d') for d in summary['example_missing_dates']])}")
        found_stations = True

if not found_stations:
    print("ไม่พบสถานีที่มีข้อมูลหายไปตั้งแต่ 20% ขึ้นไป")

สถานีที่มีข้อมูลหายไปมากกว่าหรือเท่ากับ 20%:
- สถานี BPLA: ข้อมูลหายไป 20.39%
  ตัวอย่างวันที่หายไป: 2012-01-02, 2012-01-04, 2012-01-05, 2012-08-15, 2012-08-16

In [29]:
original_stations = set(Dailyrain['station_code'].unique())
input_stations = set(input['Node'].unique())

stations_not_included_in_filtered_data = original_stations - input_stations

if stations_not_included_in_filtered_data:
    print(f"สถานีที่ไม่ได้ถูกคัดออก (ไม่ได้อยู่ใน input file) มีทั้งหมด {len(stations_not_included_in_filtered_data)} สถานี ได้แก่:")
    for station in sorted(list(stations_not_included_in_filtered_data)):
        print(f"- {station}")
else:
    print("ไม่มีสถานีใดใน Dailyrain ที่ไม่ได้ถูกคัดออกจากการกรองด้วย input file")

สถานีที่ไม่ได้ถูกคัดออก (ไม่ได้อยู่ใน input file) มีทั้งหมด 1002 สถานี ได้แก่:
- ABRT
- AIT001
- AIT002
- AIT003
- AIT004
- AIT005
- AIT006
- AIT007
- AIT008
- AIT009
- AIT010
- AIT011
- ATG011
- ATG021
- ATG031
- ATG032
- ATG042
- ATG051
- ATG052
- ATG072
- ATG081
- ATG082
- ATG091
- ATG092
- ATG101
- ATG111
- ATG112
- ATG121
- ATG122
- ATG131
- ATG132
- ATG141
- ATG142
- ATG151
- ATG152
- ATG161
- ATG162
- ATG171
- ATG181
- ATG182
- BAKI
- BARI
- BBON
- BBWN
- BCAP
- BDWN
- BGBO
- BGYN
- BHPK
- BJAN
- BKC001
- BKC002
- BKC003
- BKC004
- BKC005
- BKC006
- BKC007
- BKC008
- BKHI
- BKJO
- BKK002
- BKK003
- BKK004
- BKK005
- BKK006
- BKK012
- BKK013
- BKK016
- BKK020
- BKK021
- BKNH
- BLNG
- BMKN
- BMKO
- BMOD
- BNAK
- BNKE
- BNKK
- BNPK
- BNYM
- BOP1
- BPGD
- BPK001
- BPK003
- BPUG
- BPUN
- BSCL
- BSIK
- BSP002
- BST1
- BSVT
- BTCH
- BTGH
- BTHI
- BTTI
- BTUD
- BTUM
- BTWN
- BUGN
- BUKT
- BUSW
- CAN001
- CGKG
- CHAM
- CHAU01
- CHI001
- CHI003
- CHI006
- CHI015
- CHK001
- CHK002
- CHKG
- CHM005
- CHM007
- CHN001
- CHN005
- CHR001
- CHR002
- CHR007
- CHTG
- CIHO
- CKLG
- CMKK
- CMP001
- CMP002
- CNDN
- CPON
- CPY001
- CPY002
- CPY005
- CPY006
- CPY007
- CPY008
- CPY011
- CPY014
- CPY016
- DDSO
- DIWO
- DKMU
- DMS001
- DNP034
- DNP035
- DOCI
- FANG
- FOP001
- FOP002
- FOP003
- FOP004
- FOP005
- FOP006
- FOP007
- FOP008
- FOP009
- FOP010
- FOP011
- FOP012
- FOP013
- FOP014
- FOP015
- FOP016
- FOP017
- FOP018
- FOP019
- FOP020
- FOP021
- FOP022
- FOP023
- FOP024
- FOP025
- FOP026
- FOP027
- FOP028
- FOP029
- FOP030
- FOP031
- FOP032
- FOP033
- FOP034
- FOP035
- FOP036
- FOP037
- FOP038
- FOP039
- FOP040
- FOP041
- FOP042
- FOP043
- FOP044
- FOP046
- FOP047
- FOP048
- FOP049
- FOP050
- FOP051
- FOP052
- FOP053
- FOP054
- FOP055
- FOP056
- FOP057
- FOP058
- FOP059
- FOP060
- FOP061
- FOP062
- FOP063
- FOP064
- FOP065
- FOP066
- FOP067
- FOP068
- FOP069
- FOP070
- FOP071
- FOP072
- FROC01
- FROC02
- GLF001
- GLF002
- GLF003
- GOT001
- HDA001
- HDA002
- HDA003
- HDA004
- HDA005
- HHMV
- HII001
- HIKT
- HJRN1
- HKNL
- HNCG
- HOTT
- HUKT
- JNA001
- JNA002
- KCWF
- KGTP
- KHCP
- KHDM
- KHNI
- KHOG
- KIZ001
- KIZ002
- KIZ003
- KKCN
- KMCE
- KMTK
- KNDG
- KOKO
- KON001
- KON003
- KPNT
- KPPT
- KRMT
- KRN001
- KRN004
- KSKP
- KSNG
- KTUM
- KUAM
- KUBR
- KUDN
- KWN001
- KWN003
- KYKT
- LBI001
- LDKS
- LGTI
- LHOK
- LKBU
- LMKO
- LNR1
- LNSK
- MDC001
- MDC005
- MITP01
- MKG005
- MKG006
- MKKB
- MNDM
- MOU001
- MOU002
- MOU003
- MOU004
- MOU005
- MOU006
- MOU007
- MOU008
- MOU009
- MOU010
- MOU011
- MOU012
- MOU013
- MOU014
- MOU015
- MOU016
- MOU017
- MOU018
- MOU019
- MOU020
- MOU021
- MOU022
- MOU023
- MOU024
- MOU025
- MOU026
- MOU027
- MOU028
- MOU029
- MOU030
- MOU031
- MOU032
- MOU033
- MOU034
- MOU035
- MOU036
- MOU037
- MOU038
- MOU039
- MOU040
- MOU041
- MOU042
- MOU043
- MOU044
- MOU045
- MOU046
- MOU047
- MOU048
- MOU049
- MOU050
- MOU051
- MOU052
- MOU053
- MOU054
- MOU055
- MOU056
- MOU057
- MOU058
- MOU059
- MOU060
- MOU061
- MOU062
- MOU063
- MOU064
- MOU065
- MOU066
- MOU067
- MOU068
- MOU069
- MOU070
- MOU071
- MOU072
- MOU073
- MOU074
- MOU075
- MOU076
- MOU077
- MOU078
- MOU079
- MOU080
- MOU081
- MOU082
- MOU083
- MOU084
- MOU085
- MOU086
- MOU087
- MOU088
- MOU089
- MOU090
- MOU091
- MOU092
- MOU093
- MOU094
- MOU095
- MOU096
- MOU097
- MOU098
- MOU099
- MOU100
- MOU101
- MOU102
- MOU103
- MOU104
- MOU105
- MOU106
- MOU107
- MOU108
- MOU109
- MOU110
- MOU111
- MOU112
- MOU113
- MOU114
- MOU115
- MOU116
- MOU117
- MOU118
- MOU119
- MOU120
- MOU121
- MOU122
- MOU123
- MOU124
- MOU125
- MOU126
- MOU127
- MOU128
- MOU129
- MOU130
- MOU131
- MOU132
- MOU133
- MOU134
- MOU135
- MOU136
- MOU137
- MOU138
- MOU139
- MOU140
- MOU141
- MOU142
- MOU171
- MOU174
- MOU175
- MOU176
- MOU180
- MOU189
- MOU190
- MOU191
- MOU192
- MOU195
- MOU196
- MOU198
- MOU199
- MOU202
- MOU204
- MOU211
- MOU212
- MOU219
- MOU231
- MOU232
- MOU233
- MOU244
- MOU251
- MOU252
- MOU256
- MOU267
- MOU277
- MOU278
- MOU280
- MOU288
- MOU295
- MOU296
- MOU298
- MOU299
- MOU304
- MOU305
- MOU320
- MOU321
- MOU323
- MOU327
- MOU329
- MOU330
- MOU338
- MOU339
- MOU340
- MOU341
- MOU343
- MOU344
- MOU347
- MOU349
- MOU350
- MOU351
- MOU352
- MOU353
- MOU357
- MOU366
- MOU369
- MOU371
- MOU372
- MOU383
- MOU385
- MOU387
- MOU388
- MOU390
- MOU394
- MOU395
- MOU396
- MOU397
- MOU409
- MOU413
- MOU415
- MOU416
- MOU423
- MOU426
- MOU428
- MOU431
- MOU435
- MOU441
- MOU454
- MOU464
- MOU467
- MOU468
- MOU471
- MOU472
- MOU473
- MOU474
- MOU475
- MOU476
- MOU477
- MOU478
- MOU479
- MOU480
- MOU481
- MOU483
- MOU484
- MOU485
- MOU486
- MOU487
- MOU488
- MOU489
- MOU490
- MOU491
- MOU492
- MOU493
- MOU494
- MOU495
- MOU496
- MOU497
- MOU499
- MOU500
- MOU501
- MOU502
- MOU505
- MOU506
- MOU507
- MOU509
- MOU510
- MPBR
- MSRM
- MUN002
- MUN003
- MUN005
- MUN009
- MUN010
- MUN012
- MUNG
- MWOG
- MYA001
- MYA002
- MYA003
- MYA004
- NAN002
- NAN003
- NAN004
- NAN005
- NAN007
- NAN008
- NAN009
- NAN015
- NAN016
- NANG
- NANP
- NANT
- NASG
- NBLK
- NGPH
- NGSC
- NIKS
- NKO003
- NKO004
- NKTP
- NMKO
- NMNO
- NMUB
- NNDG
- NOKG
- NOKW
- NONA
- NOPU
- NSNO
- NTTI
- NWSO
- NYK001
- NYK008
- NYK014
- NYUN
- OMKI
- ONE001
- ONE002
- ONE003
- ONE004
- ONE005
- ONE006
- ONE007
- ONE008
- ONE009
- ONE010
- ONE011
- ONE012
- ONE013
- ONE014
- ONE015
- ONE016
- ONE017
- ONE018
- ONE019
- ONE020
- ONE021
- ONE022
- ONE023
- ONE024
- ONE025
- ONE026
- ONE027
- ONE028
- ONE029
- ONE030
- ONE033
- ONE034
- ONE035
- ONE036
- ONE037
- ONE038
- ONE039
- ONE040
- ONE041
- ONE042
- ONE043
- ONE044
- ONE045
- ONE046
- ONE047
- ONE048
- ONE049
- ONE050
- ONE051
- ONE052
- ONE053
- ONE054
- ONE055
- ONE056
- ONE057
- ONE058
- ONE059
- ONE060
- ONE061
- ONE062
- ONE063
- ONE064
- ONE065
- ONE066
- ONE067
- ONE068
- ONE069
- ONE070
- ONE071
- ONE072
- ONE073
- ONE074
- ONE075
- ONE076
- ONE077
- ONE078
- ONE079
- ONE080
- ONE081
- ONE082
- ONE083
- ONE084
- ONE085
- ONE086
- ONE087
- ONE088
- ONE089
- ONE090
- ONE091
- ONE092
- ONE093
- ONE094
- ONE095
- ONE096
- ONE097
- ONE098
- ONE099
- ONE100
- ONE101
- ONE102
- ONE103
- ONE104
- ONE105
- ONE106
- ONE107
- ONE108
- ONE109
- ONE110
- ONWR01
- ONWR02
- PADT
- PAI001
- PALU
- PANC
- PANG
- PAS003
- PAS009
- PAS010
- PAT001
- PAT002
- PATO01
- PCH001
- PCH002
- PCH003
- PCHI
- PHKD
- PIN001
- PIN002
- PIN007
- PIN008
- PIN009
- PIN010
- PIN011
- PKH1
- PKTG
- PKTI
- PLG001
- PMPA
- PNCR
- PNRN
- POCE
- POCG
- PPCH
- PPPG
- PRC001
- PRC004
- PRC005
- PRN002
- PRST
- PRUK
- PTYS
- PUAA
- PVEE
- PWA004
- PYO002
- PYO003
- PYO004
- RAJ001
- RAJ003
- RAM002
- RAWE
- RAY002
- RAY004
- RCHM
- RFBK
- RMMI
- RSK7
- SACS
- SBRS
- SDO001
- SDO002
- SDO003
- SGKM
- SGMN
- SKBI
- SKG003
- SKG004
- SKG008
- SKM001
- SKM003
- SKN001
- SKN002
- SKN003
- SKPG
- SLA001
- SLA003
- SLA007
- SNSI
- SPMI
- STH001
- STH002
- STH003
- STH006
- STH007
- STH008
- STH010
- STH012
- STH013
- STH015
- STH019
- STH020
- STH021
- STH023
- STH024
- STH026
- STH027
- STH031
- STOR
- STSK
- STU002
- STU003
- STU004
- SWR001
- SWR002
- SWR003
- SWR004
- SWR005
- SWR006
- SWR007
- SWR008
- SWR010
- SWR011
- SWR012
- SWR013
- SWR014
- SWR015
- SWR016
- SWR018
- SWR019
- SWR020
- SWR021
- SWR022
- SWR023
- SWR024
- SWR025
- SWR026
- SWR027
- SWR028
- SWR029
- SWR030
- SWR031
- SWR032
- SWR033
- SWR034
- SWR035
- SWR036
- SWR037
- SWR038
- SYKP
- TADE01
- TAKI
- TAKL
- TANA
- TARE
- TB0001
- TB0004
- TB0005
- TB0006
- TB0007
- TBR011
- TBR012
- TBR013
- TBR014
- TBR015
- TBR016
- TBR017
- TBR018
- TBR019
- TBR020
- TBR021
- TBR022
- TBW008
- TBW009
- TBW014
- TBW017
- TBW018
- TBW019
- TBW021
- TBW022
- TBW023
- TBW024
- TBW025
- TBW026
- TBW027
- TBW028
- TBW029
- TBW030
- TBW032
- TBW033
- TBW034
- TBW035
- TCP001
- TCP002
- TCP003
- TCP004
- TCP005
- TCP006
- TCP007
- TCP008
- TCP009
- TCP010
- TCP011
- TCP012
- TCP013
- TGCG
- TGLM
- THA004
- THA005
- THA007
- THA008
- THA009
- THAT
- TKP002
- TKPP
- TLMU
- TNG003
- TNG004
- TNG005
- TNG006
- TON002
- TON003
- TON004
- TPAE
- TPI003
- TPI006
- TPKO
- TRD003
- TRD004
- TRD005
- TRD006
- TRD007
- TSDO
- TSYG
- UDMS
- UPCT
- UTOG
- VLGE02
- VLGE04
- VLGE06
- VLGE08
- VLGE09
- VLGE11
- VLGE12
- VLGE13
- VLGE15
- VLGE16
- VLGE17
- VLGE19
- VLGE20
- VLGE21
- VLGE22
- VLGE24
- VLGE25
- VLGE26
- VLGE28
- VLGE30
- VLGE34
- VLGE35
- VLGE36
- VLGE37
- VLGE39
- VLGE40
- VLGE43
- VLGE44
- VLGE45
- VLGE46
- VLGE47
- VLGE48
- VLGE49
- VLGE50
- WAN003
- WAN004
- WEI011
- WEI012
- WEI021
- WEI022
- WEI041
- WEI051
- WEI052
- WEI061
- WEI062
- WEI072
- WEI081
- WEI091
- WEI092
- WEI111
- WEI112
- WEI121
- WEI122
- WEI131
- WEI132
- WEI141
- WEI142
- WEI151
- WGHG
- WGPO
- WGRY
- WGSA
- WGYG
- WSPR
- WSTG
- YBKM
- YKPC
- YOM004
- YOM005
- YOM006
- YOM007
- YOM011
- YOM013
- YOM014
- YOM015
- YOM016

# ข้อ5

In [31]:
if missing_records_summary:
    print("ตัวอย่างวันที่ข้อมูลหายไปของแต่ละสถานี:")
    for station, summary in sorted_summary:
        if summary['example_missing_dates']:
            print(f"- สถานี {station}: ตัวอย่างวันที่หายไป: {', '.join([d.strftime('%Y-%m-%d') for d in summary['example_missing_dates']])}")
else:
    print("ไม่พบข้อมูล Record ที่หายไปในสถานีใดๆ")

ตัวอย่างวันที่ข้อมูลหายไปของแต่ละสถานี:
- สถานี BPLA: ตัวอย่างวันที่หายไป: 2012-01-02, 2012-01-04, 2012-01-05, 2012-08-15, 2012-08-16
- สถานี BHMN: ตัวอย่างวันที่หายไป: 2012-01-02, 2012-03-21, 2012-03-22, 2012-03-23, 2012-03-24
- สถานี KHHM: ตัวอย่างวันที่หายไป: 2012-01-14, 2012-01-16, 2012-01-17, 2012-01-18, 2012-01-20
- สถานี BKHN: ตัวอย่างวันที่หายไป: 2012-03-13, 2012-03-14, 2012-03-15, 2012-03-16, 2012-03-17
- สถานี STH005: ตัวอย่างวันที่หายไป: 2014-05-28, 2014-08-17, 2014-08-31, 2015-04-04, 2015-04-27
- สถานี CHI011: ตัวอย่างวันที่หายไป: 2012-12-01, 2012-12-02, 2012-12-03, 2012-12-04, 2012-12-05
- สถานี KHPB: ตัวอย่างวันที่หายไป: 2012-01-02, 2012-01-04, 2012-01-05, 2012-07-06, 2012-07-07
- สถานี BKWN: ตัวอย่างวันที่หายไป: 2012-01-02, 2012-01-04, 2012-01-05, 2012-06-02, 2012-06-03
- สถานี NKO001: ตัวอย่างวันที่หายไป: 2012-06-22, 2012-06-23, 2012-06-24, 2012-06-25, 2012-06-26
- สถานี PAS002: ตัวอย่างวันที่หายไป: 2014-09-25, 2014-09-26, 2014-09-27, 2014-09-28, 2014-09-29
- สถานี SAY002: ตัวอย่างวันที่หายไป: 2012-06-22, 2012-06-23, 2012-06-24, 2012-06-25, 2012-06-26
- สถานี KOKN: ตัวอย่างวันที่หายไป: 2012-01-02, 2012-01-04, 2012-01-05, 2014-03-30, 2014-04-25
- สถานี TKRA: ตัวอย่างวันที่หายไป: 2012-01-02, 2012-01-04, 2012-01-05, 2013-09-12, 2013-09-13
- สถานี BNMK: ตัวอย่างวันที่หายไป: 2012-08-01, 2012-08-02, 2012-08-03, 2012-08-04, 2012-08-05
- สถานี WTLG: ตัวอย่างวันที่หายไป: 2012-01-02, 2012-01-03, 2012-01-04, 2012-01-05, 2012-05-13
- สถานี NKOK: ตัวอย่างวันที่หายไป: 2012-01-02, 2012-01-09, 2012-01-10, 2012-01-11, 2012-01-12
- สถานี STH029: ตัวอย่างวันที่หายไป: 2013-06-08, 2013-06-09, 2013-06-10, 2013-06-11, 2013-06-12
- สถานี BPPS: ตัวอย่างวันที่หายไป: 2012-01-02, 2012-01-03, 2012-01-04, 2012-01-05, 2012-11-30
- สถานี VLGE07: ตัวอย่างวันที่หายไป: 2012-03-01, 2012-03-02, 2012-03-03, 2012-03-04, 2012-03-05
- สถานี STH017: ตัวอย่างวันที่หายไป: 2012-12-17, 2012-12-18, 2012-12-19, 2012-12-20, 2012-12-21
- สถานี KKHA: ตัวอย่างวันที่หายไป: 2012-01-02, 2012-01-04, 2012-01-05, 2012-08-21, 2012-08-22
- สถานี NKYG: ตัวอย่างวันที่หายไป: 2012-01-04, 2012-01-05, 2012-03-27, 2012-08-02, 2012-08-31
- สถานี SGKW: ตัวอย่างวันที่หายไป: 2012-01-02, 2012-01-04, 2012-01-05, 2012-11-30, 2014-04-26
- สถานี THNM: ตัวอย่างวันที่หายไป: 2012-01-02, 2012-07-27, 2012-07-28, 2012-07-29, 2012-07-30
- สถานี TPTN: ตัวอย่างวันที่หายไป: 2012-01-02, 2012-01-04, 2012-01-05, 2013-12-16, 2013-12-17
- สถานี TTWY: ตัวอย่างวันที่หายไป: 2012-01-02, 2012-01-04, 2012-01-05, 2014-03-16, 2014-04-13
- สถานี BNHI: ตัวอย่างวันที่หายไป: 2012-01-02, 2012-01-04, 2013-01-29, 2013-01-30, 2013-01-31
- สถานี DITO: ตัวอย่างวันที่หายไป: 2012-01-02, 2012-01-04, 2012-01-05, 2012-09-12, 2012-09-13
- สถานี BNTK: ตัวอย่างวันที่หายไป: 2012-01-02, 2012-01-04, 2012-01-05, 2012-11-30, 2014-04-27
- สถานี SKKG: ตัวอย่างวันที่หายไป: 2012-01-02, 2012-01-04, 2012-01-05, 2012-06-15, 2012-06-16
- สถานี NKSG: ตัวอย่างวันที่หายไป: 2012-01-02, 2012-01-04, 2012-01-05, 2012-03-27, 2012-07-08
- สถานี MEWG: ตัวอย่างวันที่หายไป: 2012-01-02, 2012-03-27, 2012-04-08, 2012-04-09, 2012-04-10
- สถานี KAOP: ตัวอย่างวันที่หายไป: 2012-01-02, 2012-11-30, 2013-10-30, 2014-03-30, 2014-04-27
- สถานี BNPI: ตัวอย่างวันที่หายไป: 2012-11-30, 2013-11-01, 2013-11-02, 2013-11-03, 2013-11-04
- สถานี STWN: ตัวอย่างวันที่หายไป: 2012-01-02, 2012-01-04, 2012-01-05, 2012-06-19, 2012-06-20
- สถานี STH014: ตัวอย่างวันที่หายไป: 2014-06-10, 2015-04-04, 2015-04-27, 2016-05-10, 2016-06-04
- สถานี NAPK: ตัวอย่างวันที่หายไป: 2012-01-02, 2012-01-04, 2012-01-05, 2012-03-27, 2012-04-28
- สถานี DKLG: ตัวอย่างวันที่หายไป: 2012-01-02, 2012-01-04, 2012-01-05, 2012-03-25, 2012-03-26
- สถานี MRMT: ตัวอย่างวันที่หายไป: 2012-01-02, 2012-01-04, 2012-01-05, 2012-03-27, 2014-04-27
- สถานี MDTG: ตัวอย่างวันที่หายไป: 2012-03-12, 2012-03-13, 2012-03-14, 2012-03-15, 2012-03-16
- สถานี KKTO: ตัวอย่างวันที่หายไป: 2012-01-02, 2012-01-04, 2012-01-05, 2012-07-08, 2012-07-09
- สถานี LNRG: ตัวอย่างวันที่หายไป: 2012-01-02, 2012-01-03, 2012-01-04, 2012-01-05, 2012-03-27
- สถานี TTLG: ตัวอย่างวันที่หายไป: 2012-01-02, 2012-01-04, 2012-01-05, 2013-12-30, 2013-12-31
- สถานี BYNU: ตัวอย่างวันที่หายไป: 2012-11-30, 2013-11-04, 2013-11-05, 2013-11-06, 2013-11-07
- สถานี CHR003: ตัวอย่างวันที่หายไป: 2014-04-06, 2015-07-06, 2015-07-07, 2015-07-08, 2015-07-09
- สถานี WNKH: ตัวอย่างวันที่หายไป: 2012-12-15, 2012-12-16, 2012-12-17, 2012-12-18, 2012-12-19
- สถานี YOM009: ตัวอย่างวันที่หายไป: 2013-07-29, 2013-07-30, 2013-07-31, 2013-08-01, 2013-08-02
- สถานี KTKB: ตัวอย่างวันที่หายไป: 2012-01-04, 2012-01-08, 2012-01-11, 2012-01-12, 2012-01-13
- สถานี SNGT: ตัวอย่างวันที่หายไป: 2012-01-02, 2012-01-04, 2012-07-11, 2012-07-12, 2012-07-13
- สถานี VLGE27: ตัวอย่างวันที่หายไป: 2013-05-19, 2014-03-16, 2014-04-13, 2015-02-25, 2015-02-26
- สถานี NPI001: ตัวอย่างวันที่หายไป: 2012-03-27, 2013-09-10, 2013-09-11, 2013-09-12, 2013-09-13
- สถานี STH018: ตัวอย่างวันที่หายไป: 2014-06-08, 2014-08-27, 2015-04-04, 2015-04-27, 2015-09-01
- สถานี BNHG: ตัวอย่างวันที่หายไป: 2012-01-02, 2012-01-04, 2012-01-05, 2012-06-26, 2012-06-27
- สถานี WRRS: ตัวอย่างวันที่หายไป: 2012-01-04, 2012-01-05, 2012-01-07, 2012-01-08, 2012-03-29
- สถานี CPY017: ตัวอย่างวันที่หายไป: 2012-06-12, 2012-06-13, 2012-06-14, 2012-06-15, 2012-06-16
- สถานี TUKW: ตัวอย่างวันที่หายไป: 2012-01-04, 2012-01-08, 2012-01-09, 2012-01-10, 2012-01-11
- สถานี CHI005: ตัวอย่างวันที่หายไป: 2012-04-12, 2012-04-13, 2012-04-17, 2012-04-18, 2012-04-19
- สถานี CGMN: ตัวอย่างวันที่หายไป: 2012-09-28, 2012-09-29, 2012-09-30, 2012-10-01, 2012-10-02
- สถานี DIV001: ตัวอย่างวันที่หายไป: 2013-09-29, 2013-09-30, 2013-10-01, 2013-10-02, 2013-10-03
- สถานี BKK008: ตัวอย่างวันที่หายไป: 2012-06-14, 2012-06-15, 2012-06-16, 2012-06-17, 2012-06-18
- สถานี SRKT: ตัวอย่างวันที่หายไป: 2012-01-02, 2012-01-04, 2012-01-05, 2012-09-19, 2012-09-20
- สถานี CHUN: ตัวอย่างวันที่หายไป: 2012-01-02, 2012-01-04, 2012-01-05, 2012-08-26, 2012-08-27
- สถานี PRN001: ตัวอย่างวันที่หายไป: 2014-05-20, 2014-05-21, 2014-05-22, 2014-05-23, 2014-05-24
- สถานี TRON: ตัวอย่างวันที่หายไป: 2012-04-17, 2012-04-18, 2012-04-19, 2012-04-20, 2012-04-21
- สถานี TPI002: ตัวอย่างวันที่หายไป: 2014-04-13, 2014-08-21, 2014-08-22, 2014-08-23, 2014-08-24
- สถานี PIN004: ตัวอย่างวันที่หายไป: 2012-11-10, 2012-11-11, 2012-11-12, 2012-11-13, 2012-11-14
- สถานี WCTK: ตัวอย่างวันที่หายไป: 2012-01-02, 2012-01-04, 2014-03-16, 2014-04-01, 2014-04-13
- สถานี PASG: ตัวอย่างวันที่หายไป: 2012-01-02, 2012-01-03, 2012-01-04, 2012-01-05, 2012-11-30
- สถานี KMSI: ตัวอย่างวันที่หายไป: 2012-01-02, 2012-01-04, 2012-01-05, 2013-04-26, 2013-04-27
- สถานี NTNG: ตัวอย่างวันที่หายไป: 2012-07-03, 2012-07-04, 2012-07-05, 2012-07-06, 2012-07-08
- สถานี SBT1: ตัวอย่างวันที่หายไป: 2012-01-02, 2012-01-04, 2012-01-05, 2012-11-30, 2014-04-26
- สถานี DGSL: ตัวอย่างวันที่หายไป: 2012-01-02, 2012-01-04, 2012-01-05, 2012-11-07, 2012-11-08
- สถานี STU001: ตัวอย่างวันที่หายไป: 2012-06-22, 2012-06-23, 2012-06-24, 2012-06-25, 2012-06-26
- สถานี BKHL: ตัวอย่างวันที่หายไป: 2012-01-02, 2012-01-04, 2012-01-05, 2014-04-27, 2014-12-25
- สถานี CPY012: ตัวอย่างวันที่หายไป: 2013-07-31, 2013-08-01, 2013-08-02, 2013-08-03, 2013-08-04
- สถานี THA006: ตัวอย่างวันที่หายไป: 2012-06-14, 2012-06-15, 2012-06-16, 2012-06-17, 2012-06-18
- สถานี SSRG: ตัวอย่างวันที่หายไป: 2012-09-29, 2012-09-30, 2012-10-01, 2012-10-02, 2012-10-03
- สถานี WAN002: ตัวอย่างวันที่หายไป: 2012-03-24, 2012-03-25, 2014-03-16, 2014-04-01, 2014-04-13
- สถานี THA003: ตัวอย่างวันที่หายไป: 2012-06-13, 2012-06-14, 2012-06-15, 2012-06-16, 2012-06-17
- สถานี KNYM: ตัวอย่างวันที่หายไป: 2012-01-04, 2012-01-05, 2012-04-16, 2012-04-17, 2012-04-18
- สถานี JBLG: ตัวอย่างวันที่หายไป: 2012-01-02, 2012-01-04, 2012-01-05, 2012-10-13, 2012-10-14
- สถานี HCTT: ตัวอย่างวันที่หายไป: 2012-01-02, 2012-01-03, 2012-01-04, 2012-01-05, 2012-11-30
- สถานี HYRT: ตัวอย่างวันที่หายไป: 2012-01-02, 2012-01-04, 2012-01-05, 2012-07-06, 2012-07-07
- สถานี STH011: ตัวอย่างวันที่หายไป: 2015-04-04, 2015-04-27, 2015-06-30, 2016-02-29, 2016-05-10
- สถานี STH022: ตัวอย่างวันที่หายไป: 2013-10-18, 2013-10-19, 2013-10-20, 2013-10-21, 2013-10-22
- สถานี TNG002: ตัวอย่างวันที่หายไป: 2012-06-22, 2012-06-23, 2012-06-24, 2012-06-25, 2012-06-26
- สถานี KGKG: ตัวอย่างวันที่หายไป: 2012-06-26, 2012-06-27, 2012-06-28, 2012-06-29, 2012-06-30
- สถานี NASW: ตัวอย่างวันที่หายไป: 2012-01-02, 2012-01-04, 2012-01-05, 2012-02-26, 2012-02-27
- สถานี BLAT: ตัวอย่างวันที่หายไป: 2012-01-02, 2012-01-04, 2012-01-05, 2014-04-27, 2014-12-25
- สถานี KANG: ตัวอย่างวันที่หายไป: 2012-04-26, 2012-04-27, 2012-04-28, 2012-04-29, 2012-04-30
- สถานี HNKA: ตัวอย่างวันที่หายไป: 2012-01-02, 2012-01-04, 2012-03-28, 2012-03-29, 2012-03-30
- สถานี KON002: ตัวอย่างวันที่หายไป: 2012-06-16, 2012-06-17, 2012-06-18, 2012-06-19, 2012-06-20
- สถานี KON005: ตัวอย่างวันที่หายไป: 2012-06-16, 2012-06-17, 2012-06-18, 2012-06-19, 2012-06-20
- สถานี YCUM: ตัวอย่างวันที่หายไป: 2012-01-02, 2012-01-04, 2012-01-05, 2013-08-06, 2013-08-07
- สถานี THCG: ตัวอย่างวันที่หายไป: 2012-01-02, 2012-01-04, 2012-01-05, 2014-04-13, 2014-04-26
- สถานี BLKO: ตัวอย่างวันที่หายไป: 2013-06-05, 2013-06-07, 2013-06-08, 2013-06-09, 2013-06-10
- สถานี KOSR: ตัวอย่างวันที่หายไป: 2012-01-02, 2012-01-04, 2012-01-05, 2014-03-30, 2014-04-27
- สถานี RBPI: ตัวอย่างวันที่หายไป: 2012-01-02, 2012-01-04, 2012-01-05, 2012-03-27, 2012-11-30
- สถานี TSUD: ตัวอย่างวันที่หายไป: 2014-03-16, 2014-04-13, 2014-04-27, 2014-07-15, 2014-07-16
- สถานี BPTG: ตัวอย่างวันที่หายไป: 2012-01-02, 2012-01-04, 2012-01-05, 2012-11-30, 2013-08-06
- สถานี MECN: ตัวอย่างวันที่หายไป: 2012-05-12, 2012-05-13, 2012-05-14, 2012-05-15, 2012-05-16
- สถานี BPIA: ตัวอย่างวันที่หายไป: 2012-01-02, 2012-01-04, 2012-01-05, 2012-11-30, 2014-02-06
- สถานี CHI010: ตัวอย่างวันที่หายไป: 2013-05-23, 2013-05-24, 2013-05-25, 2013-05-26, 2013-05-27
- สถานี BHRA: ตัวอย่างวันที่หายไป: 2012-01-02, 2012-01-03, 2012-01-04, 2012-01-05, 2014-04-27
- สถานี TEPT: ตัวอย่างวันที่หายไป: 2012-01-02, 2012-01-03, 2012-01-04, 2012-01-05, 2012-01-22
- สถานี TPPN: ตัวอย่างวันที่หายไป: 2012-01-02, 2012-01-04, 2012-01-05, 2012-10-29, 2012-10-30
- สถานี CEHM: ตัวอย่างวันที่หายไป: 2012-01-02, 2012-01-03, 2012-01-04, 2012-01-05, 2012-11-30
- สถานี BNAN: ตัวอย่างวันที่หายไป: 2012-07-03, 2012-07-04, 2012-07-07, 2012-07-09, 2012-07-11
- สถานี TPUR: ตัวอย่างวันที่หายไป: 2012-01-02, 2012-01-03, 2012-01-04, 2012-01-05, 2012-07-03
- สถานี DMKH: ตัวอย่างวันที่หายไป: 2012-01-02, 2012-11-30, 2014-04-06, 2014-04-14, 2014-04-27
- สถานี SAY001: ตัวอย่างวันที่หายไป: 2012-06-22, 2012-06-23, 2012-06-24, 2012-06-25, 2012-06-26
- สถานี STH004: ตัวอย่างวันที่หายไป: 2015-04-04, 2015-04-27, 2016-05-10, 2016-06-04, 2016-06-17
- สถานี PONG: ตัวอย่างวันที่หายไป: 2012-01-14, 2012-01-16, 2012-01-17, 2012-01-18, 2012-01-20
- สถานี STH030: ตัวอย่างวันที่หายไป: 2014-04-13, 2015-04-04, 2015-04-27, 2015-07-22, 2015-09-01
- สถานี NSRS: ตัวอย่างวันที่หายไป: 2012-01-02, 2012-01-03, 2012-01-04, 2012-01-05, 2012-03-27
- สถานี CPY009: ตัวอย่างวันที่หายไป: 2012-08-31, 2012-09-01, 2012-09-02, 2012-09-03, 2012-09-04
- สถานี BDAR: ตัวอย่างวันที่หายไป: 2012-01-02, 2012-01-04, 2012-01-05, 2012-10-31, 2013-06-05
- สถานี THTN: ตัวอย่างวันที่หายไป: 2012-01-02, 2012-01-04, 2012-01-05, 2012-10-30, 2012-10-31
- สถานี BKUG: ตัวอย่างวันที่หายไป: 2012-01-02, 2012-01-03, 2012-01-04, 2012-01-05, 2014-04-27
- สถานี BSDE: ตัวอย่างวันที่หายไป: 2012-01-02, 2012-11-30, 2014-04-27, 2016-05-11, 2016-09-08
- สถานี NMKH: ตัวอย่างวันที่หายไป: 2012-11-30, 2013-05-25, 2013-05-26, 2013-05-27, 2013-05-28
- สถานี BSUM: ตัวอย่างวันที่หายไป: 2012-01-02, 2012-07-04, 2012-07-05, 2012-07-06, 2012-07-07
- สถานี TPI005: ตัวอย่างวันที่หายไป: 2014-04-13, 2016-05-10, 2016-07-01, 2016-07-02, 2016-07-26
- สถานี LBI002: ตัวอย่างวันที่หายไป: 2012-06-16, 2012-06-17, 2012-06-18, 2012-06-19, 2012-06-20
- สถานี CTKN: ตัวอย่างวันที่หายไป: 2012-01-02, 2012-01-04, 2012-01-05, 2012-11-30, 2014-04-06
- สถานี HYOD: ตัวอย่างวันที่หายไป: 2012-01-02, 2012-01-04, 2012-01-05, 2012-11-30, 2014-03-30
- สถานี TNG001: ตัวอย่างวันที่หายไป: 2012-06-20, 2012-06-21, 2012-06-22, 2012-06-23, 2012-06-24
- สถานี TKNT: ตัวอย่างวันที่หายไป: 2012-05-22, 2012-05-23, 2012-05-24, 2012-05-25, 2012-05-26
- สถานี PIN003: ตัวอย่างวันที่หายไป: 2015-04-04, 2015-04-27, 2015-05-27, 2016-05-11, 2016-05-12
- สถานี CHM001: ตัวอย่างวันที่หายไป: 2012-06-22, 2012-06-23, 2012-06-24, 2012-06-25, 2012-06-26
- สถานี CMSG: ตัวอย่างวันที่หายไป: 2012-11-30, 2014-04-06, 2014-04-27, 2014-07-16, 2014-07-17
- สถานี BBHN: ตัวอย่างวันที่หายไป: 2012-01-02, 2012-01-04, 2012-01-05, 2012-10-31, 2014-04-02
- สถานี CPKC: ตัวอย่างวันที่หายไป: 2012-01-02, 2012-01-03, 2012-01-04, 2012-01-05, 2012-11-30
- สถานี MCRM: ตัวอย่างวันที่หายไป: 2012-01-02, 2012-01-04, 2012-01-05, 2012-03-27, 2012-06-20
- สถานี PRC002: ตัวอย่างวันที่หายไป: 2012-07-03, 2012-07-04, 2012-07-05, 2012-07-06, 2012-07-07
- สถานี SKG002: ตัวอย่างวันที่หายไป: 2012-06-14, 2012-06-15, 2012-06-16, 2012-06-17, 2012-06-18
- สถานี CGKM: ตัวอย่างวันที่หายไป: 2012-01-02, 2012-11-30, 2014-04-27, 2015-04-22, 2015-09-15
- สถานี HKTG: ตัวอย่างวันที่หายไป: 2012-01-02, 2012-01-04, 2012-01-05, 2012-11-30, 2014-03-30
- สถานี PIN006: ตัวอย่างวันที่หายไป: 2013-09-13, 2013-09-14, 2013-09-15, 2013-09-16, 2013-09-17
- สถานี BSPN: ตัวอย่างวันที่หายไป: 2012-11-30, 2014-04-27, 2016-05-11, 2017-02-04, 2017-04-08
- สถานี KWSI: ตัวอย่างวันที่หายไป: 2012-01-02, 2012-01-04, 2012-01-05, 2012-03-27, 2014-04-26
- สถานี CHR005: ตัวอย่างวันที่หายไป: 2014-01-31, 2014-02-01, 2014-02-02, 2014-02-03, 2014-02-04
- สถานี YOM001: ตัวอย่างวันที่หายไป: 2013-04-01, 2013-04-02, 2013-04-03, 2013-04-04, 2013-04-05
- สถานี CGSN: ตัวอย่างวันที่หายไป: 2012-07-03, 2012-07-04, 2012-07-05, 2012-07-06, 2012-07-07
- สถานี NAKU: ตัวอย่างวันที่หายไป: 2012-01-02, 2012-01-04, 2012-01-05, 2012-03-27, 2012-05-15
- สถานี PAS008: ตัวอย่างวันที่หายไป: 2015-03-21, 2015-03-22, 2015-03-23, 2015-03-24, 2015-03-25
- สถานี TPI001: ตัวอย่างวันที่หายไป: 2013-02-14, 2013-02-15, 2013-02-16, 2013-02-17, 2013-02-18
- สถานี WSPN: ตัวอย่างวันที่หายไป: 2012-01-03, 2012-01-04, 2012-07-03, 2012-07-04, 2012-07-05
- สถานี BSKJ: ตัวอย่างวันที่หายไป: 2012-11-30, 2014-04-27, 2016-05-11, 2016-09-08, 2016-09-09
- สถานี YGHM: ตัวอย่างวันที่หายไป: 2012-01-02, 2012-01-05, 2013-03-31, 2013-04-01, 2013-04-02
- สถานี SENM: ตัวอย่างวันที่หายไป: 2012-01-02, 2012-01-05, 2012-11-30, 2013-05-20, 2013-05-21
- สถานี PAS001: ตัวอย่างวันที่หายไป: 2013-11-03, 2013-11-04, 2013-11-05, 2013-11-06, 2013-11-07
- สถานี SISU: ตัวอย่างวันที่หายไป: 2012-01-02, 2012-11-30, 2014-04-27, 2015-04-04, 2016-05-11
- สถานี BKK019: ตัวอย่างวันที่หายไป: 2014-12-25, 2016-01-30, 2016-01-31, 2016-02-01, 2016-02-02
- สถานี SITP: ตัวอย่างวันที่หายไป: 2012-01-02, 2012-01-04, 2012-01-05, 2012-11-30, 2014-04-27
- สถานี NAN013: ตัวอย่างวันที่หายไป: 2016-05-11, 2016-06-17, 2016-06-29, 2016-07-01, 2016-07-02
- สถานี BKK001: ตัวอย่างวันที่หายไป: 2012-06-16, 2012-06-17, 2012-06-18, 2012-06-19, 2012-06-20
- สถานี LK13: ตัวอย่างวันที่หายไป: 2012-01-02, 2012-01-04, 2012-01-05, 2012-03-27, 2013-02-16
- สถานี BMNK: ตัวอย่างวันที่หายไป: 2012-01-02, 2012-01-03, 2012-01-04, 2012-01-05, 2012-01-08
- สถานี CLPK: ตัวอย่างวันที่หายไป: 2012-01-02, 2012-01-05, 2012-06-22, 2012-06-23, 2012-06-24
- สถานี CPY013: ตัวอย่างวันที่หายไป: 2014-04-06, 2014-04-14, 2014-07-03, 2015-04-17, 2015-06-27
- สถานี NGCG: ตัวอย่างวันที่หายไป: 2012-07-09, 2012-07-10, 2012-07-11, 2012-07-12, 2012-07-13
- สถานี NEAK: ตัวอย่างวันที่หายไป: 2012-01-02, 2012-01-04, 2012-01-05, 2012-03-27, 2014-04-26
- สถานี PMPN: ตัวอย่างวันที่หายไป: 2012-01-02, 2012-01-04, 2012-01-05, 2012-03-27, 2012-11-30
- สถานี VLGE03: ตัวอย่างวันที่หายไป: 2014-01-02, 2014-01-03, 2014-01-04, 2014-01-05, 2014-01-06
- สถานี PHON: ตัวอย่างวันที่หายไป: 2012-01-02, 2012-01-04, 2012-01-05, 2012-11-30, 2014-04-27
- สถานี LPLE: ตัวอย่างวันที่หายไป: 2012-01-02, 2012-01-04, 2012-01-05, 2012-03-27, 2014-04-27
- สถานี PSLI: ตัวอย่างวันที่หายไป: 2012-01-02, 2012-01-04, 2012-03-27, 2012-11-30, 2014-04-27
- สถานี PAII: ตัวอย่างวันที่หายไป: 2012-01-02, 2012-01-03, 2012-01-04, 2012-01-05, 2012-11-30
- สถานี SOKL: ตัวอย่างวันที่หายไป: 2012-01-02, 2012-01-04, 2012-01-05, 2012-11-30, 2014-04-27
- สถานี MNRM: ตัวอย่างวันที่หายไป: 2012-01-02, 2012-01-04, 2012-01-05, 2012-03-27, 2014-04-27
- สถานี BSMP: ตัวอย่างวันที่หายไป: 2012-02-04, 2012-02-05, 2012-02-06, 2012-02-07, 2012-02-08
- สถานี BKK009: ตัวอย่างวันที่หายไป: 2012-06-14, 2012-06-15, 2012-06-16, 2012-06-17, 2012-06-18
- สถานี WTCH: ตัวอย่างวันที่หายไป: 2012-01-02, 2012-07-12, 2012-07-13, 2012-07-14, 2012-07-15
- สถานี BNGR: ตัวอย่างวันที่หายไป: 2012-01-02, 2012-01-05, 2012-01-09, 2012-01-10, 2012-01-11
- สถานี CHHA: ตัวอย่างวันที่หายไป: 2012-01-02, 2012-01-04, 2012-01-05, 2012-07-03, 2012-07-04
- สถานี DIV002: ตัวอย่างวันที่หายไป: 2013-09-26, 2013-09-27, 2013-09-28, 2013-09-29, 2013-09-30
- สถานี NBON: ตัวอย่างวันที่หายไป: 2012-01-02, 2012-01-04, 2012-01-05, 2012-03-27, 2013-01-03
- สถานี SKE002: ตัวอย่างวันที่หายไป: 2015-04-04, 2016-03-05, 2016-03-06, 2016-03-07, 2016-03-08
- สถานี VLGE01: ตัวอย่างวันที่หายไป: 2012-12-23, 2012-12-24, 2012-12-25, 2012-12-26, 2012-12-27
- สถานี NNKO: ตัวอย่างวันที่หายไป: 2012-01-02, 2012-01-04, 2012-01-05, 2012-07-03, 2012-07-04
- สถานี NAN006: ตัวอย่างวันที่หายไป: 2012-03-27, 2013-09-20, 2013-09-21, 2013-09-22, 2013-09-23
- สถานี NAN001: ตัวอย่างวันที่หายไป: 2012-01-13, 2012-01-15, 2012-03-27, 2012-09-13, 2012-10-27
- สถานี STH016: ตัวอย่างวันที่หายไป: 2014-05-12, 2014-07-13, 2015-04-04, 2015-04-27, 2015-09-01
- สถานี TTKO: ตัวอย่างวันที่หายไป: 2012-01-02, 2012-01-04, 2012-01-05, 2012-07-13, 2012-07-14
- สถานี SWNG: ตัวอย่างวันที่หายไป: 2012-01-02, 2012-01-05, 2012-07-04, 2012-07-05, 2012-07-06
- สถานี SKE003: ตัวอย่างวันที่หายไป: 2015-04-04, 2016-05-11, 2016-05-12, 2016-06-04, 2016-06-17
- สถานี PGKH: ตัวอย่างวันที่หายไป: 2012-01-02, 2012-11-30, 2014-04-27, 2014-04-28, 2014-04-29
- สถานี MKTR: ตัวอย่างวันที่หายไป: 2012-01-02, 2012-01-04, 2012-01-05, 2012-03-27, 2012-09-18
- สถานี WAN001: ตัวอย่างวันที่หายไป: 2012-04-10, 2012-04-11, 2014-03-16, 2014-04-01, 2014-04-13
- สถานี NAN014: ตัวอย่างวันที่หายไป: 2016-01-26, 2016-01-27, 2016-01-28, 2016-01-29, 2016-01-30
- สถานี YOM008: ตัวอย่างวันที่หายไป: 2012-03-11, 2012-03-12, 2012-03-13, 2012-03-15, 2012-03-16
- สถานี RAJ002: ตัวอย่างวันที่หายไป: 2013-02-09, 2013-02-10, 2013-02-11, 2013-02-12, 2013-02-13
- สถานี SVI002: ตัวอย่างวันที่หายไป: 2014-04-13, 2015-02-28, 2015-04-27, 2015-04-30, 2016-06-04
- สถานี KON004: ตัวอย่างวันที่หายไป: 2014-03-30, 2014-05-23, 2014-07-03, 2014-07-04, 2014-07-05
- สถานี PSLT: ตัวอย่างวันที่หายไป: 2012-11-30, 2013-12-27, 2013-12-28, 2013-12-29, 2013-12-30
- สถานี BLUG: ตัวอย่างวันที่หายไป: 2012-01-02, 2012-01-03, 2012-01-05, 2014-02-18, 2014-02-19
- สถานี KGLN: ตัวอย่างวันที่หายไป: 2012-01-02, 2012-01-03, 2012-01-04, 2012-01-05, 2012-11-30
- สถานี WBYN: ตัวอย่างวันที่หายไป: 2012-01-02, 2012-01-04, 2012-01-05, 2014-03-16, 2014-04-01
- สถานี BTHO: ตัวอย่างวันที่หายไป: 2012-01-02, 2012-01-04, 2012-01-05, 2012-11-30, 2013-05-03
- สถานี CBUR: ตัวอย่างวันที่หายไป: 2012-01-27, 2012-01-28, 2012-01-29, 2012-01-30, 2012-01-31
- สถานี NPNK: ตัวอย่างวันที่หายไป: 2012-01-02, 2012-01-04, 2012-01-05, 2012-03-27, 2012-11-30
- สถานี RIKK: ตัวอย่างวันที่หายไป: 2012-04-17, 2012-04-18, 2012-04-19, 2012-04-20, 2012-04-21
- สถานี YOM010: ตัวอย่างวันที่หายไป: 2013-01-22, 2013-01-23, 2013-01-24, 2013-01-25, 2013-01-26
- สถานี CGDO: ตัวอย่างวันที่หายไป: 2012-01-02, 2012-01-03, 2012-01-04, 2012-01-05, 2012-11-30
- สถานี PAI002: ตัวอย่างวันที่หายไป: 2015-04-04, 2015-04-27, 2015-11-20, 2015-11-21, 2015-11-22
- สถานี WGTG: ตัวอย่างวันที่หายไป: 2012-01-02, 2012-01-04, 2012-01-05, 2013-05-05, 2013-05-06
- สถานี BKK017: ตัวอย่างวันที่หายไป: 2014-12-25, 2016-05-11, 2016-07-01, 2016-07-02, 2016-07-05
- สถานี LMSK: ตัวอย่างวันที่หายไป: 2012-01-04, 2012-01-05, 2012-03-27, 2014-04-27, 2015-04-27
- สถานี PDAM: ตัวอย่างวันที่หายไป: 2012-01-02, 2012-01-04, 2012-01-05, 2012-03-24, 2012-03-25

In [35]:
# Make a copy to work with, to avoid modifying the original filtered_Dailyrain directly
filtered_Dailyrain_imputed = filtered_Dailyrain.copy()

# Extract Day of Year for grouping
filtered_Dailyrain_imputed['day_of_year'] = filtered_Dailyrain_imputed['measure_datetime'].dt.dayofyear

# Calculate median 'data' for each station_code and day_of_year
median_rainfall_by_day = filtered_Dailyrain_imputed.groupby(['station_code', 'day_of_year'])['data'].median().reset_index()
median_rainfall_by_day.rename(columns={'data': 'median_data'}, inplace=True)

# Merge the median values back into the main DataFrame
filtered_Dailyrain_imputed = pd.merge(
    filtered_Dailyrain_imputed,
    median_rainfall_by_day,
    on=['station_code', 'day_of_year'],
    how='left'
)

# Fill NaN values in 'data' column with 'median_data'
filtered_Dailyrain_imputed['data'] = filtered_Dailyrain_imputed['data'].fillna(filtered_Dailyrain_imputed['median_data'])

# Drop the temporary 'day_of_year' and 'median_data' columns
filtered_Dailyrain_imputed.drop(columns=['day_of_year', 'median_data'], inplace=True)

print("แสดงข้อมูล 5 แถวแรกหลังจากเติมค่าที่หายไปด้วยค่ามัธยฐาน:")
display(filtered_Dailyrain_imputed.head())

แสดงข้อมูล 5 แถวแรกหลังจากเติมค่าที่หายไปด้วยค่ามัธยฐาน:

,station_code,measure_datetime,data,station_name,latitude,longitude,quality_flag,basin,sub_basin,tambon,amphoe,province,data_type
0,ACRU,2012-01-01 07:00:00+07:00,0.0,ทต.ไก่คำ,15.788054,104.642235,U,มูล,ลำเซบก,ไก่คำ,เมืองอำนาจเจริญ,อำนาจเจริญ,rainfall_daily
1,ACRU,2012-01-06 07:00:00+07:00,0.0,ทต.ไก่คำ,15.788054,104.642235,U,มูล,ลำเซบก,ไก่คำ,เมืองอำนาจเจริญ,อำนาจเจริญ,rainfall_daily
2,ACRU,2012-01-07 07:00:00+07:00,0.0,ทต.ไก่คำ,15.788054,104.642235,U,มูล,ลำเซบก,ไก่คำ,เมืองอำนาจเจริญ,อำนาจเจริญ,rainfall_daily
3,ACRU,2012-01-08 07:00:00+07:00,0.0,ทต.ไก่คำ,15.788054,104.642235,U,มูล,ลำเซบก,ไก่คำ,เมืองอำนาจเจริญ,อำนาจเจริญ,rainfall_daily
4,ACRU,2012-01-09 07:00:00+07:00,0.0,ทต.ไก่คำ,15.788054,104.642235,U,มูล,ลำเซบก,ไก่คำ,เมืองอำนาจเจริญ,อำนาจเจริญ,rainfall_daily

In [34]:
print("ตรวจสอบว่ายังมีค่าที่หายไปในคอลัมน์ 'data' หรือไม่หลังจากเติม:")
print(filtered_Dailyrain_imputed['data'].isnull().sum())

ตรวจสอบว่ายังมีค่าที่หายไปในคอลัมน์ 'data' หรือไม่หลังจากเติม:
0

# ข้อ6



จากการดำเนินการแทนค่าข้อมูลที่หายไปในตัวแปรวันเดือนปี พบว่าการเลือกใช้ค่า มัธยฐาน (median) มีความเหมาะสมมากกว่าการใช้ค่าเฉลี่ย (mean) เนื่องจากลักษณะของข้อมูลวันเดือนปีมีการกระจายที่ไม่สมมาตรและมีความเป็นไปได้ที่จะพบค่าผิดปกติ (outliers) เช่น วันที่ที่เก่าหรือใหม่ผิดจากช่วงเวลาหลักของข้อมูล ซึ่งค่าเฉลี่ยมีความไวต่อค่าผิดปกติดังกล่าว อาจส่งผลให้ค่าที่นำมาแทนไม่สะท้อนค่ากลางที่แท้จริงของข้อมูล

ในขณะที่ค่า median เป็นค่ากลางตามลำดับของข้อมูล จึงไม่ได้รับอิทธิพลจากค่าที่มีความแตกต่างอย่างมาก ทำให้ค่าที่แทนลงไปมีความใกล้เคียงกับแนวโน้มของข้อมูลเดิมมากกว่า นอกจากนี้ ข้อมูลวันเดือนปีจัดเป็นข้อมูลเชิงลำดับตามเวลา การใช้ median จึงสามารถแทนค่ากลางของช่วงเวลาได้อย่างเหมาะสม และช่วยรักษาโครงสร้างการกระจายของข้อมูลไว้ได้

ดังนั้น การใช้ค่า median ในการแทนค่าที่หายไปของข้อมูลวันเดือนปีจึงช่วยลดความบิดเบือนของข้อมูลหลังการประมวลผล และเพิ่มความน่าเชื่อถือของผลการวิเคราะห์ในขั้นตอนถัดไป เมื่อเปรียบเทียบกับการใช้ค่า mean ซึ่งอาจทำให้ค่าที่แทนมีความคลาดเคลื่อนจากสภาพความเป็นจริงของข้อมูล

# ข้อ7

In [36]:
monthly_rainfall = filtered_Dailyrain_imputed[filtered_Dailyrain_imputed['station_code'] != 'BPLA']
print("แสดงข้อมูล 5 แถวแรกหลังจากกรองสถานี 'BPLA' ออก:")
display(monthly_rainfall.head())

แสดงข้อมูล 5 แถวแรกหลังจากกรองสถานี 'BPLA' ออก:

,station_code,measure_datetime,data,station_name,latitude,longitude,quality_flag,basin,sub_basin,tambon,amphoe,province,data_type
0,ACRU,2012-01-01 07:00:00+07:00,0.0,ทต.ไก่คำ,15.788054,104.642235,U,มูล,ลำเซบก,ไก่คำ,เมืองอำนาจเจริญ,อำนาจเจริญ,rainfall_daily
1,ACRU,2012-01-06 07:00:00+07:00,0.0,ทต.ไก่คำ,15.788054,104.642235,U,มูล,ลำเซบก,ไก่คำ,เมืองอำนาจเจริญ,อำนาจเจริญ,rainfall_daily
2,ACRU,2012-01-07 07:00:00+07:00,0.0,ทต.ไก่คำ,15.788054,104.642235,U,มูล,ลำเซบก,ไก่คำ,เมืองอำนาจเจริญ,อำนาจเจริญ,rainfall_daily
3,ACRU,2012-01-08 07:00:00+07:00,0.0,ทต.ไก่คำ,15.788054,104.642235,U,มูล,ลำเซบก,ไก่คำ,เมืองอำนาจเจริญ,อำนาจเจริญ,rainfall_daily
4,ACRU,2012-01-09 07:00:00+07:00,0.0,ทต.ไก่คำ,15.788054,104.642235,U,มูล,ลำเซบก,ไก่คำ,เมืองอำนาจเจริญ,อำนาจเจริญ,rainfall_daily

In [38]:
monthly_rainfall['year'] = monthly_rainfall['measure_datetime'].dt.year
monthly_rainfall['month'] = monthly_rainfall['measure_datetime'].dt.month
print("แสดงข้อมูล 5 แถวแรกหลังจากเพิ่มคอลัมน์ 'year' และ 'month':")
display(monthly_rainfall.head())

แสดงข้อมูล 5 แถวแรกหลังจากเพิ่มคอลัมน์ 'year' และ 'month':

/tmp/ipython-input-4007610658.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  monthly_rainfall['year'] = monthly_rainfall['measure_datetime'].dt.year
/tmp/ipython-input-4007610658.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  monthly_rainfall['month'] = monthly_rainfall['measure_datetime'].dt.month

,station_code,measure_datetime,data,station_name,latitude,longitude,quality_flag,basin,sub_basin,tambon,amphoe,province,data_type,year,month
0,ACRU,2012-01-01 07:00:00+07:00,0.0,ทต.ไก่คำ,15.788054,104.642235,U,มูล,ลำเซบก,ไก่คำ,เมืองอำนาจเจริญ,อำนาจเจริญ,rainfall_daily,2012,1
1,ACRU,2012-01-06 07:00:00+07:00,0.0,ทต.ไก่คำ,15.788054,104.642235,U,มูล,ลำเซบก,ไก่คำ,เมืองอำนาจเจริญ,อำนาจเจริญ,rainfall_daily,2012,1
2,ACRU,2012-01-07 07:00:00+07:00,0.0,ทต.ไก่คำ,15.788054,104.642235,U,มูล,ลำเซบก,ไก่คำ,เมืองอำนาจเจริญ,อำนาจเจริญ,rainfall_daily,2012,1
3,ACRU,2012-01-08 07:00:00+07:00,0.0,ทต.ไก่คำ,15.788054,104.642235,U,มูล,ลำเซบก,ไก่คำ,เมืองอำนาจเจริญ,อำนาจเจริญ,rainfall_daily,2012,1
4,ACRU,2012-01-09 07:00:00+07:00,0.0,ทต.ไก่คำ,15.788054,104.642235,U,มูล,ลำเซบก,ไก่คำ,เมืองอำนาจเจริญ,อำนาจเจริญ,rainfall_daily,2012,1

In [39]:
monthly_rainfall = filtered_Dailyrain_imputed[filtered_Dailyrain_imputed['station_code'] != 'BPLA'].copy()

monthly_rainfall['year'] = monthly_rainfall['measure_datetime'].dt.year
monthly_rainfall['month'] = monthly_rainfall['measure_datetime'].dt.month

monthly_rainfall_sum = monthly_rainfall.groupby(['station_code', 'year', 'month'])['data'].sum().reset_index()

monthly_rainfall_sum.rename(columns={'station_code': 'Node', 'data': 'rain'}, inplace=True)

monthly_rainfall_sum = monthly_rainfall_sum[['Node', 'rain', 'month', 'year']]

print("แสดงข้อมูล 5 แถวแรกของปริมาณน้ำฝนรายเดือนหลังจากประมวลผล:")
display(monthly_rainfall_sum.head())

แสดงข้อมูล 5 แถวแรกของปริมาณน้ำฝนรายเดือนหลังจากประมวลผล:

   Node   rain  month  year
0  ACRU    5.8      1  2012
1  ACRU    0.0      2  2012
2  ACRU   13.4      3  2012
3  ACRU  167.0      4  2012
4  ACRU  250.2      5  2012

In [40]:
from google.colab import files

# Save the DataFrame to a CSV file
csv_filename = 'monthly_rainfall_sum.csv'
monthly_rainfall_sum.to_csv(csv_filename, index=False)

print(f"ไฟล์ '{csv_filename}' ถูกสร้างเรียบร้อยแล้วค่ะ")

# Provide a download link
files.download(csv_filename)

ไฟล์ 'monthly_rainfall_sum.csv' ถูกสร้างเรียบร้อยแล้วค่ะ

# ไฟลผลลัพธ์ GDrive และ บันทึกการใช้ AI

https://drive.google.com/file/d/1e1875NBH6r5Ymn411v9JBoqAcXxvJZUE/view?usp=sharing

[ข้อความลิงก์](https://)

In [43]:
from google.colab import files

print("กรุณาเลือกไฟล์ที่คุณต้องการอัปโหลด:")
uploaded = files.upload()

for fn in uploaded.keys():
  print(f'User uploaded file "{fn}" with length {len(uploaded[fn])} bytes')

กรุณาเลือกไฟล์ที่คุณต้องการอัปโหลด:

Saving monthly_rainfall_sum.csv to monthly_rainfall_sum (1).csv
User uploaded file "monthly_rainfall_sum (1).csv" with length 1099175 bytes

## AI prompt

https://docs.google.com/document/d/1tvI8l84L_rnKwNF0cRl-maFUc3o_08-ie6xFvqAnW0A/edit?usp=sharing